### PR TITLE
Atomic TLC / Compiler Warning Fixes

### PR DESCRIPTION
**Pull request by IBNobody**
I improved on the existing Atomic keymaps by leveraging the Planck maps. I also corrected some compiler warnings.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Nice :) you have that dual function key functionality on your planck/pc keymap - does that work for you?

I've never gotten that to work, so I've been working on a way to do it otherwise... I thought I had it committed somewhere, but can't find it right now.

**Comment by jackhumbert** [comment]
[Found it](https://github.com/jackhumbert/qmk_firmware/blob/user_functions/keyboard/planck/keymaps/lock/keymap.c#L93) - I called it "tri layer," but am open to better names.

**Comment by IBNobody** [comment]
... Did I leave that in? Blargh... No, I haven't gotten it to work yet. I stopped meddling with it to get my Atomic up. And while doing so, my Planck layout slipped in.

But now that I've got a working Atomic... That'll be next.

**Comment by jackhumbert** [comment]
:) I'm a fan of making olkb-wide PC/Mac layouts instead of just having the default (similar to how the EZ does it), so I'm open to you and @NoahAndrews's input on that!

I'd like to work in an official tri-layer functionality before the next revision gets produced. Now that I think about it, that needs to be done soon - like tomorrow.

**Comment by IBNobody** [comment]
I was playing around with it last night. I thought the problem would be that layer hopping clears out keypresses. Thus, how can you have an on-release macro fire?

Haha, My layouts weren't named for my computer choice.

**Comment by IBNobody** [comment]
Ha. Ok. Yes, the tri-layer was what I was about to implement last night, and I was going to do it by reading the enabled layers rather than use an additional static/global.

There needs to be a `IS_LAYER_ON(layer)` macro/function added to action_layer.c/.h

**Comment by jackhumbert** [comment]
I like that idea! I would imagine it has some other uses as well. I'm guessing it'd just be 

    #define IS_LAYER_ON(layer) (layer_state & (1<<layer))

right? I'm not sure if we'd need to look at the default_layer_state.

**Comment by NoahAndrews** [comment]
What exactly are we talking about with "tri-layer"?

**Comment by IBNobody** [comment]
@jackhumbert 

```
#define IS_LAYER_ON(layer) (layer_state & (1<<(layer)))
```

Maybe add a IS_LAYER_OFF macro too, even though it is equal to !IS_LAYER_ON.

@NoahAndrews 

This is useful if you want to activate layers via two fingers. You'd typically put functions here that you wouldn't want to accidentally invoke. (Oh crap! I'm in Dvorak! Oh crap! I'm in the bootloader!)

Here is the expected behavior.

- Pressing & holding Raise takes you to the Raised layer.
- Pressing & holding Lower takes you to the Lower layer.
- Pressing & holding Raise and then pressing & holding Lower takes you to a Function (FN0) layer.

Or... Another useful approach:

- Pressing & holding Raise takes you to the Raised layer.
- Pressing & holding Lower takes you to the Lower layer.
- Pressing & holding Raise and then pressing & holding Lower takes you to the FN1 layer. 
- Pressing & holding Lower and then pressing & holding Raise takes you to the FN2 layer.

Both have the same release actions:

- Releasing Raise takes you to the Lower layer if you are in a FN layer, and back to the default layer if you are in the Raised layer.
- Releasing Lower takes you to the Raised layer if you are in a FN layer, and back to the default layer if you are in the Lower layer.

**Comment by NoahAndrews** [comment]
Ah, cool!

**Comment by jackhumbert** [comment]
So the "raise" and "lower" keys refer to the registers/ledgers that used to be on typewriters - what would a third one be called?

**Comment by mecanogrh** [comment]
Funny I implemented this today making a Vim mode with visual mode within, though it uses 'v' to jump to the visual layer and 'esc' to go back to the normal mode layer. Going back to the default layer is of course achieved by pressed 'i' (ie insert in Vim). I had to use a bool function variable, I get the layer state through get_mods() because OSX text selections are made with Shift but indeed there is a need for something like a get_layer() function.

**Comment by IBNobody** [comment]
I have an uncommitted prototype that is working and uses the IS_LAYER_ON macro. I was able to switch to a third layer, and also was able to switch to a third or fourth layer.

**Comment by jackhumbert** [comment]
Nice! That's awesome. 

I'm leaning towards "adjust", after "shift", "raise", and "lower" - also because it adjusts the keyboard with low-level actions. 

@IBNobody I'm working on things now too - can I see what you're doing and run with it if you're at a spot you can commit?

**Comment by IBNobody** [comment]
https://github.com/IBNobody/qmk_firmware/blob/personal_atomic_planck/keyboard/atomic/keymaps/pvc_atomic.c

**Comment by IBNobody** [comment]
I was in the process of trying to make things more intuitive.

**Comment by jackhumbert** [comment]
Nice. Implemented that along with what I'm working on [here](https://github.com/jackhumbert/qmk_firmware/blob/new_defaults/keyboard/planck/keymaps/default/keymap.c)! Gonna think things through a bit, do the Preonic's in a similar way, then merge things in.

**Comment by jackhumbert** [comment]
We should probably figure out a good way to decide whether or not the layers that trigger the tri-layer should be turned off - KC_TRNS falling to the previous layer (raise in this case) isn't very intuitive. I may just make them KC_NO for clarity.

**Comment by IBNobody** [comment]
That was the conclusion I came to when I was thinking about it too. Use trans or NO in the keylayer itself lends to more flexibity during layer creation...

**Comment by IBNobody** [comment]
From @eltang

```
#define IS_LAYER_ON(layer) (layer_state & (1UL << (layer)))
#define IS_LAYER_OFF(layer) (!IS_LAYER_ON(layer))
```

**Comment by ezuk** [comment]
Just chiming in to say I think there should be a doc update along with this change, to cover the functionality with some examples in the Readme. 

Also, just out of curiosity, does this bring us closer to chording?

**Comment by jackhumbert** [comment]
Yeah! We should pair on the docs soon :) I'll have the Makefile stuff in #255 done soon too.

Not sure about chording on this - not a whole lot of new functionality really comes out of it vs what the chording would be doing.

**Comment by mecanogrh** [comment]
Beautiful :)

**Pull request merged**
