### PR TITLE
ergodox_ez for emacs + mac + altgr users

### PR DESCRIPTION
**Pull request by Willyfrog**

### CODE REVIEW

**Comment by ezuk** [comment]
@Willyfrog - love this! One question: The Readme includes a link to an image, but there is no image as part of the pull request?

**Comment by Willyfrog** [comment]
oh! I planned to add an image (I think it's really useful) bur I haven't done it yet. I'll try to do it later and add it to the PR

**Comment by Willyfrog** [comment]
image added, thanks for noticing :smile:

**Comment by ezuk** [comment]
Awesome! Thank you, merging!

**Pull request merged**
