### PR TITLE
Change NKRO Report Size = 32, User Print

### PR DESCRIPTION
**Pull request by IBNobody**

### CODE REVIEW

**Comment by IBNobody** [comment]
I changed how MAGIC_HOST_NKRO works. It now also enables NKRO. @jackhumbert , need some guidance on this. TMK_CORE uses keyboard_nkro, and QMK uses both keyboard_nkro for the protocols and keymap_config.nkro for the EEPROM. Should we use keymap_config.nkro for all?

**Comment by IBNobody** [comment]
User print disables the normal print messages in the body of QMK/TMK code and is meant as a lightweight alternative to NOPRINT. Use it when you only want to do a spot of debugging but lack flash resources for allowing all of the codebase to print (and store their wasteful strings).

**Comment by jackhumbert** [comment]
Awesome :)

**Comment by algernon** [comment]
Thanks to UPRINT, @IBNobody! I shaved off 1320 bytes from my keymap thans to it!

**Comment by IBNobody** [comment]
@algernon I know! It's wonderful. I was able to get console out and audio to fit onto my Planck. The cost of uprint is only 200b because it eliminated all the wasteful string defines sprinkled throughout QMK/TMK.

We just need to become the uprint police and make sure nobody sticks uprint calls in the QMK/TMK framework. Only print/xprintf and dprint should be allowed in.

**Pull request merged**
