### PR TITLE
Add docker-compose for easy docker use.

### PR DESCRIPTION
**Pull request by pvdvreede**
Making it easier to use docker without needing to re-type long docker commands over and over.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Sweet! Is there any reason this references edasque/qmk_firmware instead of jackhumbert/qmk_firmware?

**Comment by pvdvreede** [comment]
No, I just copied the docker image name from the readme. I will update this PR with the jackhumbert/qmk_firmware image!

**Comment by jackhumbert** [comment]
Ah, cool! Thanks!

**Comment by pvdvreede** [comment]
@jackhumbert I just tried to add the docker image as you suggested and docker-compose said it couldnt find it.

I checked docker hub and it didnt come up in a search: https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=qmk_firmware&starCount=0

Is that the correct name for it?

**Comment by jackhumbert** [comment]
Ah, sorry - I just added it! https://hub.docker.com/r/jackhumbert/qmk_firmware/

**Comment by ezuk** [comment]
So I must say I'm not completely sold on using docker-compose here. As the docs say, "Compose is a tool for defining and running multi-container Docker applications." It's really for that kind of work -- setting up a more complex env etc., not just for the syntactic command-line sugar.

I do agree that the docker docs need some loving. That command line is convoluted and it doesn't even use our dockerfile but pulls that image. Jack and I are on it.

**Pull request closed without merging**
