### PR TITLE
Establish QMK support for Phantom TKL keyboard

### PR DESCRIPTION
**Pull request by TerryMathews**
ANSI 125 layout, capslock and scrolllock implemented, support for
WS2812LED strip included.

Compiles and is running as expected on my Phantom.

### CODE REVIEW

**Comment by eltang** [comment]
Wow, I wasn't sure if my code for scanning matrices with reversed diodes actually worked. Thanks for testing it.

**Comment by TerryMathews** [comment]
Yeah, works like a charm and has for a while - I've been working off an older branch that I forked off of a0-c clear back when QMK hadn't yet integrated WS2812 support.

For what it's worth, whoever claimed to have improved debounce support in matrix.c, it's working as well. I had to run DEBOUNCE 3 on the old source tree to keep the Phantom from dropping keystrokes, it doesn't drop one anymore with DEBOUNCE 5.

**Comment by eltang** [comment]
Just so we're clear, I'm talking about #343, which is pretty recent. I haven't changed QMK's debouncing code much—the speedup you experienced was probably because I made the code faster in general. I actually did make some changes to the debouncing code which are not part of QMK yet because I wasn't sure if anyone else would notice if it made a difference. It would be great if you'd be willing to try it out.

**Comment by jackhumbert** [comment]
Sweet - thanks!

**Comment by TerryMathews** [comment]
@eltang sure, I'd be glad to be a guinea pig

**Comment by eltang** [comment]
@TerryMathews Thanks! The branch, into which I've just merged the changes from this PR, is [here](https://github.com/eltang/qmk_firmware/tree/debouncing_fix).

**Comment by TerryMathews** [comment]
r is undefined in matrix_scan in the else condition and compiling is
failing. Looking at the other code, I'm assuming it should be an int8_t,
but I'm too tired tonight to figure out how and where it should be
initialized. Let me know when you get it worked out and I'll merge the PR.

**Comment by jackhumbert** [comment]
Hey guys - please move this discussion to it's own area :) thanks.

**Pull request merged**
