### PR TITLE
Virtual Serial Port - and a Layout that uses that virtual serial port for Plover

### PR DESCRIPTION
**Pull request by SmackleFunky**
This adds support for a virtual serial usb device. It appears along side the other HID devices when enabled.
It is useful for being able to send over usb serial instead of as a HID device, in case you ever need such a thing.,

In my case, I wanted to use a serial device to emulate a Stenograph machine to be used in plover. This is implemented for the ergodox, but can easily be adapted for others.

Macro functions can be used to send whatever you need over serial.

### CODE REVIEW

**Comment by SmackleFunky** [comment]
Is there a way to define a layout to be only for Ergodox Ez, now that the paths have been merged? Unfortunately this doesn't work with Infinity due to the different base code.

**Comment by fredizzimo** [comment]
You should be able to add a keymaps folder inside the EZ subfolder, and add your keymap to that subfolder. Keymaps there will be EZ only.

**Comment by fredizzimo** [comment]
I will try to port this to the Infinity at some point, as I don't see any reason why it wouldn't be possible to do there too.

Of course someone else can do that too, but in that case, please notify me before you start, otherwise we might do duplicate work.

**Comment by SmackleFunky** [comment]
Great thanks, I'll make the change once I've tested all-keyboards again.
Should be doable there also, I just hadn't looked at the non-lufa code yet

**Comment by algernon** [comment]
I love this, a lot. Looking forward to trying it!

**Comment by jackhumbert** [comment]
This is awesome! Thanks for adding this :)

**Pull request merged**
