### PR TITLE
Makefile optimization

### PR DESCRIPTION
**Pull request by fredizzimo**
This greatly reduces the build times. Two major optimizations have been applied.

1. Got rid of recursive make calls, since it's very slow to parse the make files. This is done by adding proper dependencies for some of the targets. The begin and end magic string outputs are also removed, since it would have been hard to support properly, and shouldn't be needed anyway.
2. Don't run git describe for every make file command, this speeds up the compilation itself

And of course to speed it up even more, you should run make in parallel like this ´make -jx --output-sync`, where x is the number of processors you would like to use. This works for all make targets.

### CODE REVIEW

**Comment by fredizzimo** [comment]
Closing and re-opening since travis didn't start

**Comment by fredizzimo** [comment]
Hm.. Travis still doesn't start even after closing and re-opening?

**Comment by fredizzimo** [comment]
Ok, it took some time

**Comment by fredizzimo** [comment]
Seems like it's randomly failing for all-keyboards, it was fine for all-keymaps. I'll try to find out what the reason is.

**Comment by fredizzimo** [comment]
Seems like the Travis builds got around twice as fast. It could probably be speeded up even more by setting -j2 to the make, as there should be two cores https://docs.travis-ci.com/user/ci-environment/.

**Comment by fredizzimo** [comment]
I added the option to, so don't merge yet before it's tested.

**Comment by fredizzimo** [comment]
Ok, the jobserver is not available, so -j2 doesn't work on the build machine. I will rebase the pull request to remove the travis changes.

**Comment by fredizzimo** [comment]
Ok, seems like it realized that everything is already compiled, so this should now be OK to merge.

**Comment by jackhumbert** [comment]
Awesome! Thanks for doing this :)

**Comment by fredizzimo** [comment]
Yeah, the difference in compile speed is even greater on my machine, since I don't have an SSD, and I'm also running through cygwin, and add that Git is slower on Windows. And of course I'm able to compile it with the 8 cores that I have.

I had to check what was wrong, because it took "ages" to run a quick build with no changes. And then I didn't really see any differences from making it parallel until I found the GIT command.

**Comment by fredizzimo** [comment]
Seems like I might have messed something up. The quick command doesn't detect that dependent h files are updated.

**Comment by fredizzimo** [comment]
I'm very sorry for that. And it seems like it will take me a while to find the reason and fix it. As a workaround, don't use quick make commands until it's fixed.

**Comment by fredizzimo** [comment]
It seems like I didn't break it. It's broken for sub-projects before my commit too. It's probably related to the build output paths. In any case I'm looking into it, and will fix it.

**Pull request merged**
