### PR TITLE
Minor cleanup to refer to SYMB and MDIA in default ergodox_ez keymap rather than hard-coding numbers.

### PR DESCRIPTION
**Pull request by agriffis**

### CODE REVIEW

**Comment by DidierLoiseau** [comment]
As a cleanup, I think the `KC_FN1` in layer 0 could also be replaced by `MO(SYMB)`, which would allow to remove the entry in `fn_actions`.

**Comment by ezuk** [comment]
@agriffis - looking good! Just to confirm: You compiled+tested and it works?

**Comment by agriffis** [comment]
@ezuk Yes.

@DidierLoiseau True, in fact that's what I'm doing in my personal keymap (not submitted). It has the side-effect of lighting the LED for the momentary press, which is kinda cool. Please feel free to put in a separate PR; I'm not planning to update this one.

**Comment by ezuk** [comment]
@agriffis awesome! Merged! :)

**Pull request merged**
