### PR TITLE
Got rid of all the kludge in my ErgoDox keymap.

### PR DESCRIPTION
**Pull request by Xyverz**
Updated keymap.c with new code.
Updated readme.md to reflect this compatibility change.

Special thanks to u/algernone for the tips that made this work.

### CODE REVIEW

**Comment by algernon** [comment]
Glad you could make it work!

(<- /u/algernone)

**Comment by fredizzimo** [comment]
What problem exactly does this try to resolve? I don't think we should need to do any workarounds in the keyboard files to get things work.

If you describe the problem better, I can find a better way to do it during the weekend.

**Comment by fredizzimo** [comment]
I guess it's related to this pull request https://github.com/jackhumbert/qmk_firmware/pull/650, and the reasons for it failing?

**Comment by Xyverz** [comment]
Correct. It didn't fail, just spewed a ton of warnings. Now it no longer spews out warnings.

**Comment by fredizzimo** [comment]
Ok, I will have a look tomorrow. 

Also you don't need to open new pull requests to apply fixes to existing ones. Just push new commits and the pull request will update.

**Comment by Xyverz** [comment]
This is a new request because Jack already merged 650.

**Comment by fredizzimo** [comment]
Ah, ok

**Comment by fredizzimo** [comment]
I didn't wait until tomorrow. The problem is that you don't use the `KEYMAP` macro for defining your layout, but defining it manually without it.

The Infinity and the EZ have totally different matrices internally, for example different numbers of rows and columns, so that's why you get warnings about excess elements. This means that even if the Infinity compiles with this change, the keymap would be totally messed up.

Another advantage of using the KEYMAP macro is that you can define the keymaps in a form that very closely represents the physical layout. So you don't have to swap the columns and rows like you do in your keymaps.

Changing this would mean that you have to change all your layers though.

**Comment by Xyverz** [comment]
I have no problem changing it as long as I can keep the persistent layers. If that functionality goes away reverting to a conventional keymap file, then I'm really not interested.

**Comment by algernon** [comment]
If by persistent layers you mean that if you switch to another layer, and that persists through a reboot - that works with the macro too. All the `KEYMAP` macro does, is translate keys to positions. Your layers, and functionality remain the same.

**Comment by Xyverz** [comment]
Huh. I thought it was done the way Jack had done it for the Planck and
Preonic. I'll close this pull request then and redo my keymap this weekend
then.

**Comment by jackhumbert** [comment]
Yeah, sorry - it's done that way for the Planck/Preonic because the matrix is much simplier. The `KEYMAP` macro is much more useful in boards like the Ergodox :)

**Comment by Xyverz** [comment]
It's no problem. I've said it before - I'm not a programmer. I'll learn eventually. ;-) I'll get my Dox layout redone, then check on the other three boards I've submitted keymaps for to see if their keymaps will benefit from using the KEYMAP macro.

**Comment by Xyverz** [comment]
I've gotten rid of all the kludge in my ErgoDox keymap. I actually feel better now.

The persistent layers still persist. YAY!

**Comment by jackhumbert** [comment]
Awesome :)

**Pull request merged**
