### PR TITLE
ergodox: Update algernon's keymap to v1.6

### PR DESCRIPTION
**Pull request by algernon**
### Base layer changes

* The parentheses & bracket keys have been merged: tapping them results in `[` or `{` (if it was shifted), double tapping leads to `(`.
* The `:;` and `-_` keys are now available on the base layer, on their **ADORE** location, too, just below `[{(`/`]})`.
* The `Apps` key has been replaced by `F12`.
* The `-`/`_` is no longer a tap-dance key.

### ADORE layer changes

* Adjustments were made to the **ADORE** layer, to separate some inconvenient combinations.

### Miscellaneous changes

* `LEAD u` now starts the symbolic unicode input system, instead of the OS-one.
* The mouse acceleration keys on the **Navigation and Media* layer have been turned into toggles: tap them once to turn them on, until tapped again. Tapping an accelerator button will turn all the others off.
* When the **ARROW** layer is on, the *red* and *blue* LEDs light up now.

### Heatmap

* The built-in keylogger has been greatly enhanced, it now outputs the pressed state, and the layer (Dvorak or ADORE). As such, the `ADORE_AUTOLOG` option has been removed, instead there is `AUTOLOG_ENABLE` now, which when enabled, makes the keylogger start when the keyboard boots. It defaults to off.
* The heatmap generator received a lot of updates.

### CODE REVIEW

**Comment by fredizzimo** [comment]
It appears like the `qk_ucis_state` definition should be moved to `process_unicode.c` instead of `process_unicode.h` to avoid getting it declared in multiple objects. And of course make the declaration extern.

**Comment by algernon** [comment]
Hm. How did I not spot this?

**Comment by fredizzimo** [comment]
Maybe because the error only happens on Infinity for some reason, but without a much deeper investigation I have no idea why.

**Comment by algernon** [comment]
#679 should fix the error, it does so locally. Thanks @fredizzimo for the hint!

**Comment by algernon** [comment]
There we go, rebased on top of current master, all green!

**Comment by ezuk** [comment]
@fredizzimo all good here? 

Thank you @algernon! Your keymaps are a form of art :)

**Comment by fredizzimo** [comment]
@ezuk, yes. I see no other problems than that this keymap is so good that it makes me wish that I had more time to make my own :+1:

**Comment by ezuk** [comment]
Yay! Merging (fashionably late, very sorry for that).

**Pull request merged**
