### PR TITLE
Adding nicer Infinity build instructions.

### PR DESCRIPTION
**Pull request by linsomniac**
I spent some time struggling with updating my Ez keymap to work with the Infinity, and I hoped my notes could help someone else, even though I haven't quite gotten it finished.  This took me a couple of hours to figure all of it out.

### CODE REVIEW

**Comment by fredizzimo** [comment]
Although the instructions are nice, I don't think @ezuk, will accept this, as it puts priority of Infinity over the EZ.

Maybe we should just split the file into two different ones, if the current structure is too complicated? So there would be one readme.md, that is nothing more than a short general description with a link to readme_ez.md, and readme_infinity.md.

But yes, you are right, the part about flashing the separate halves is missing. BTW, for the right hand part the process is exactly the same. Just plug that part to the computer directly. 

By default it it requires the left hand to be connected to the computer, but if you you add MASTER=right to the make command, the halves can be swapped.

**Comment by r2d2rogers** [comment]
On the flashing two halves: You can flash each half with the firmware that makes it master with no ill effects. Then, if you plug the set in with the other side direct to the PC, it all still works correctly.

**Comment by linsomniac** [comment]
I've done a complete restructuring of the readme to get rid of any favoritism, though the Ez is still listed first.  Thanks for the feedback everyone.

**Comment by Xyverz** [comment]
Looks easy to read for me. I never knew about removing the .build directory. I always assumed `make keymap=[keymap] clean` would take care of that...

**Comment by fredizzimo** [comment]
@Xyverz Yes clean should take care of it. Also with the recent make file changes (a couple of weeks ago) it should correctly detect which files needs re-compilation, even when you specify make file variables by the command line. So even clean shouldn't be necessary. If it doesn't, then please open a bug.

@linsomniac, Therefore I suggest that you remove that step from the readme.

For the submodules, I suggest that we add this to the instructions `git submodule sync --recursive`, which should be done before `git submodule update --init --recursive`. We don't need to add the reason to the readme, but if the submodules ever change location from the default, you would need to run that line to resync them. That could easily happen since currently we are using only the official repositories, but if there's a bug that we need to fix, then we need to fork them, and then the location would change.

Both of these commands should **always** be run, each time you pull new updates. It's also often needed if you switch branches.

You also got the left hand/right hand instructions wrong, the `MASTER` option only affects the half that is connected to your computer.

For more information, see the instructions that I wrote before the Infinity Ergodox was ported to QMK . https://github.com/fredizzimo/infinity_ergodox. The "Physical Connection" section describes the `MASTER` part. Most of the other instructions there also still applies. The visualizer stuff is unfortunately not yet fully ported though.

Another unrelated suggestion, is to put back more of the "easy way" description. Now it's just reduced to a single line of text and a link. For many people(maybe most), that should be the primary way of using QMK. They should just need to download an existing firmware and flash it. And the instructions for that need to be clear even for non-technical people. 

Finally I would move the current introduction text, which describes the other options to the bottom. Otherwise, at least for me it looks like, it reads "if the other options are good enough, use them", which I'm pretty sure that at least @ezuk, doesn't want, as QMK is the official firmware for Ergodox EZ.

**Comment by linsomniac** [comment]
@fredizzimo: Thanks for the feedback.  I've removed the .build removal from the instructions.  I did that just to make sure I didn't have any artifacts laying around, as at one point I got a firmware that I thought was the right one but was an older one, this was directly in the ergodox directory and I had to pull it from the .build directory.  I don't recall the details though.

The left/right thing I still don't understand, and I got to where I'm at via the statement in the "infinity_ergodox" document that says:

    For simple layout updates, you only need to flash the master(left) half. But each time there's a new firmware version or if you want to make some visualization changes, you need to flash them both.

The instructions I came up with are my interpretation of "flash them both".

The introduction text was something I took from the previous readme, which I felt heavily pushed the idea of using one of the other options.  Personally, I feel like if you are at qmk_firmware, you probably just want to do that, but the previous readme seemed to promote them so I preserved that.  I'll move it to the bottom.

... but, your second to last paragraph is to add back more of the easy way, which is what I feel the first section was.  Or are you meaning the "flashing" items that were in "The Easy Way" but I have now broken out into their own section?  Maybe if I call out to those sections in the Options section?  Thoughts?

Thanks for the feedback.

**Comment by fredizzimo** [comment]
@linsomniac. Yes flashing them both is always the safe thing to do.  However you don't need to change the MASTER variable, when flashing the right side. 

On the other hand, now when I think more about it, there's no harm doing so either. In fact it could be even better, since you then have the flexibility to change the USB cable connection without needing to reflash.

Without specifying MASTER=right, the keys will be mirrored right after flashing and you only have the right hand plugged in, but as soon as you plug in both with the left hand connected to the computer, everything will be back to normal. 

So in other word, the MASTER variable only affects the keyboard half plugged to the computer.

By the **Easy Way**, I was referring to this section. And I think we want to keep this at the top, since it's the preferred way if you don't need any customization at all. Also the users reading that would most likely already be on this page http://qmk.fm/keyboards/ergodox/, so it might be a bit confusing that the link refers to itself. But some of them might of course read the the readme directly at github, or even the readme.md as a text file, so it has to server them as well.

## The Easy Way: Use an existing firmware file and just flash it (ErgoDox EZ only)

1. Download and install the [Teensy Loader](https://www.pjrc.com/teensy/loader.html). Some Linux distributions already provide a binary (may be called `teensy-loader-cli`), so you may prefer to use this.
2. Find a firmware file you like. There are [dozens of community-contributed keymaps](http://qmk.fm/keyboards/ergodox/) you can browse and download. You can also use the [Massdrop configurator](https://keyboard-configurator.massdrop.com/ext/ergodox) to create a firmware Hex file you like.
3. Download the firmware file
4. Connect the keyboard, press its Reset button (gently insert a paperclip into the hole in the top-right corner) and flash it using the Teensy loader you installed on step 1 and the firmware you downloaded.

**Comment by linsomniac** [comment]
@fredizzimo Thanks so much for describing how the flashing of the two halves works.  I will incorporate that into the readme.

For the easy way, how about if I set up a "quickstart" section that points at the other sections (finding existing firmware, flashing)?  Rather than duplicating those sections in part there?  Maybe I'm just being too DRY, but it seems like those sections have the information without being too burdensome, but if there are issues they have the details to help resolve them, plus they have options for the Infinity too.

**Comment by fredizzimo** [comment]
@linsomniac, I'll have to let @ezuk make final call for that section, and about the rest of the changes for that matter. But having a quickstart section sounds good to me.

**Comment by linsomniac** [comment]
@fredizzimo I have made changes based on your review.  Anything else I need to cover?  Can you double check my Infinity flashing section changes to make sure I got that right?  Thanks.

**Comment by fredizzimo** [comment]
Thanks, from my point of view everything looks good now.

**Comment by linsomniac** [comment]
Thanks for the help with it.

**Comment by ezuk** [comment]
This is lovely! Thank you @fredizzimo and @linsomniac, merging it in. Yay for better docs!

**Pull request merged**
