### PR TITLE
Added support for the Minorca keyboard with default layout

### PR DESCRIPTION
**Pull request by jcowgar**
This is a keyboard created by [Planc Interactive](http://www.panc.co/blog/minorcasebright-information-page) and kits are sold by [SwitchTop](http://www.switchtop.com/product/40-percent-keyboard-kits)

### CODE REVIEW

**Comment by jackhumbert** [comment]
[We have that under handwired](https://github.com/jackhumbert/qmk_firmware/tree/master/keyboards/handwired/minorca) :) this doesn't have a PCB yet, right?

**Comment by jcowgar** [comment]
Oh wow, I didn't even look in the hand wired directory, didn't even know it existed. it. You are right, it does not have a circuit board. I was kinda proud of myself for getting my first keyboard from scratch working too!

I'll close this request with this comment.

**Comment by jcowgar** [comment]
Interestingly, though, I also have a Bantam44, it is hand wired, but it lives in the top level directory?

**Comment by jackhumbert** [comment]
Ah, good catch! I'll get that moved over :) thanks!

**Pull request closed without merging**
