### PR TITLE
ErgodoxLayoutGenerator used

### PR DESCRIPTION
**Pull request by sboesebeck**
I re-created my layouts using the ErgodoxLayoutGenerator, added PNGs to all layouts, added an additional experimental layout.

### CODE REVIEW

**Comment by ezuk** [comment]
That's awesome! A few suggestions:

1) It would be cool if your tool generated ASCII legends as well, just for backwards compatibility and making it easy to read through the keymap.c file itself. What do you think?

2) As a user, I would be dying to know how you did this. How about adding a section to your readme advertising your tool? Better yet, how about adding something to the general ErgoDox EZ readme? Your own section, explaining what the tool is, where to get it, etc.? I'd love for more people to see your work.

**Comment by sboesebeck** [comment]
Hi Erez,

I did not think about the README - I will add something there... Good point! Thanks. I'd love to advertise the tool more, but I think it is not a "product" yet - you need you way round to deal with problems and such...

what do you mean by ASCII-Legend? Like a mapping from KC_SOMETHING to the corresponding ASCII-Code? Well, could be done: the only problem is, that there are a lot of KeyCodes that are just translated or combinations of others, like all the locale specific ones, DE_OSX_AE for example.

To generate an ASCII-Map would be... quite exhausting.

We should "move" this discussion maybe to the other project. I'm also quite interested in your opinion about new features and what is missing to make it most useful...

**Comment by sboesebeck** [comment]
Added some words about the ErgodoxLayoutGenerator (ELG) in the readme. Thanks for pointing that out.

**Comment by ezuk** [comment]
Awesome, and fully agreed! Opening an issue in the other project to discuss ideas further. Merging this in, thank you @sboesebeck!

**Pull request merged**
