### PR TITLE
Fix USER PRINT/NO PRINT warning w/ Bootmagic

### PR DESCRIPTION
**Pull request by IBNobody**

### CODE REVIEW

**Comment by IBNobody** [comment]
@jackhumbert I've tried the script on a few PCs now. I have corrected all the bugs I've found.

**Comment by fredizzimo** [comment]
What has happened here? It seems like several different things have been combined into the same pull request.

**Comment by IBNobody** [comment]
Yup.

Basically, I went to fix an issue with UPRINT generating errors, and in the process, I updated some docs and wrote a tool for Windows users.

**Comment by jackhumbert** [comment]
Awesome - thanks :)

**Pull request merged**
