### PR TITLE
Moves features to their own files (process_*), adds tap dance feature

### PR DESCRIPTION
**Pull request by jackhumbert**

### CODE REVIEW

**Comment by sethbc** [comment]
h make all-keyboards-quick)?

**Comment by jackhumbert** [comment]
It only picks up the default subproject (if set) - I'm kind of torn on how to handle those, but I think compiling the default layout with every subproject will be the way to go. I'm not sure if it works right now, but each keymap should be able to set a default subproject as well.

**Comment by sethbc** [comment]
Thinking about it from a testing perspective (and recognizing that you're much more familiar with your own code of course!), if each layout is supposed to work with any subproject then the tests should probably try that unless you lock a layout to specific subprojects (or you could have something that says it works for all layouts).  Just a suggestion though, and probably increases the time to complete a test by a fair amount.

**Comment by jackhumbert** [comment]
Yeah, that's what I'm worried about - each new revision/subproject adds another column in the testing matrix. Locking it per keymap would be nice, but I'd really like keymaps to develop separately from the subproject. If we can speed up the compilation a bit, I'd be happy testing all of the combinations.

**Comment by jackhumbert** [comment]
Added in #464

**Pull request merged**
