### PR TITLE
Simplified the random letter and digit generator

### PR DESCRIPTION
**Pull request by spydon**

### CODE REVIEW

**Comment by DidierLoiseau** [comment]
As `KC_1`-`KC_0` and `KC_A`-`KC_Z` are consecutive values, I guess you could even use something like

    `KC_1` + rand() % 10

and

    `KC_A` + rand() % 26

**Comment by jackhumbert** [comment]
I usually let folks maintain their own folders on here - @cbbrowne does this look ok to you, or would you rather have this been a different folder?

**Comment by spydon** [comment]
@DidierLoiseau I left it like that if people want to modify and use it for different character sets. But yours is definitely prettier if one just wants to randomize those values.

@jackhumbert Aah, I can put it in my own keymap and submit that if @cbbrowne doesn't want the changes.

**Comment by cbbrowne** [comment]
Assuming it works, that sounds like a good change to me.

Unfortunately, that doesn't seem like valid C code to me; it instead seems like some mixture of shell and maybe Python.

If I try adding that code, I get:
keymaps/cbbrowne/keymap.c: In function 'action_get_macro':
keymaps/cbbrowne/keymap.c:152:7: error: stray '`' in program
       `KC_0` + rand() % 10;
       ^
I have done a more legit C change that eliminates the switch statement.

Note the sorta oddity that the ordering isn't KC_0, KC_1, ... KC_9, but, instead, 
KC_1, KC_2, ... , KC_9, KC_0

See commit 8079dc06825371b509da245e59cbd97248589e18

**Comment by spydon** [comment]
It did work to compile and run on my board, but you might be right that it doesn't follow the C standard. I'll close this branch as you implemented it yourself. :+1:

**Comment by DidierLoiseau** [comment]
@cbbrowne Sorry, bad copy-paste, this was only intended to give the raw idea and I forgot to remove the markdown backticks. I fixed my original comment now.

**Pull request closed without merging**
