### PR TITLE
Update functions used to write to EEPROM

### PR DESCRIPTION
**Pull request by eltang**
I made a similar pull request to @tmk, but I'm afraid that the changes will take too long to trickle all they way down here.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Sweet! Thanks!

**Comment by eltang** [comment]
Did you see me mention you in the discussion at tmk/tmk_keyboard#313? I hoped to find a way I could avoid making dual pull requests like this one.

**Comment by jackhumbert** [comment]
I think that's probably the only way to go about it for now - like your commit showed initially, QMK has uses some of those things differently. In some cases, the core of TMK has changed enough that certain PRs may not apply. I'd like to pull from upstream sometime in the near future.

**Comment by eltang** [comment]
Hmm. I'm not sure what to do then. I know that development needs fast here because of product releases and such, but I also don't think it's too fair to @tmk to have to manually cherry-pick features from QMK.

**Comment by eltang** [comment]
I have a question for a future optimization. What is [all this](https://github.com/jackhumbert/qmk_firmware/blob/master/quantum/keymap_common.c#L153-L289) doing there? I feel like new action codes should have been defined and the code to handle them put in `action.c`.

**Comment by jackhumbert** [comment]
That's just kind of the nature of projects like this. It wouldn't really make sense for me to make a bunch of PRs of unwanted features, or take up his time in trying to merge them.

**Comment by jackhumbert** [comment]
This PR has derailed enough.. feel free to make a new issue ;)

**Pull request merged**
