### PR TITLE
Added my personal keymap

### PR DESCRIPTION
**Pull request by stanleylai**
Are sharing personal keymaps a thing? Feel free to close this pull request otherwise.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Yeah! It looks like you have some conflicts in your .hex files - can you revert them and recompile?

**Comment by sgoodwin** [comment]
Also am I reading this correctly that there are changes to the default layout? The RGB stuff isn't on everyone's KC60 and shouldn't be part of the default layout.

**Comment by jackhumbert** [comment]
Yeah, it looks like there are some leftovers here from #419 - if you could take care of those as well, @stanleylai, that would be awesome!

**Comment by stanleylai** [comment]
The stock KC60 files were reverted earlier, so no RGB code exists there anymore. But they seemed to have been grouped together with the RGB commits anyway. Reverted from 3f6fac4 this time, should hopefully be better and clearer.

**Comment by jackhumbert** [comment]
Awesome - thanks! :)

**Pull request merged**
