### PR TITLE
Kinesis stapelberg firmware

### PR DESCRIPTION
**Pull request by dsoto**
This pull request adds a second Kinesis Advantage keyboard variant that uses a custom controller board available on OSH Park.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Cool! Would you mind integrating this into the other Kinesis keyboard as a subproject? [The Clueboard is a good example of how this is done.](https://github.com/jackhumbert/qmk_firmware/tree/master/keyboards/clueboard) The main one can be called `advantage`, I think.

**Comment by Xyverz** [comment]
This is exactly the project I want up here! =D I'll be giving mine a second attempt shortly. I'll contact you offline about further details for connecting the thumb clusters...

**Comment by jackhumbert** [comment]
Just wanted to ping you real quick on this!

**Comment by dsoto** [comment]
I'll take a shot at the integration of the two repos.  I've looked at the Clueboard repo and think that I can put something together with some more work.

**Pull request closed without merging**
