### PR TITLE
Unicode

### PR DESCRIPTION
**Pull request by mecanogrh**
to have unicode input you need to:
- set your OS input method to UNICODE if needed
- enable unicode in your makefile
- copy the action_function from quantum/keymap_unicode.c to your
keymap.c
- set the target OS method in your keymap.c:
void matrix_init_user()
{
set_unicode_mode(UC_OSX);
}
you can then switch when you want with:
set_unicode_mode(UC_OSX);
set_unicode_mode(UC_LNX);
set_unicode_mode(UC_WIN);
- put some unicode codes in your keymap like so:
UC(0x0061)

I did change the bit mask in quantum/keymap_common.c and .h
I’m afraid we will need uint32 to get a total support for all unicode
tables or relocate the handler as @mbarkhau did.

### CODE REVIEW

**Comment by mecanogrh** [comment]
Damn 162 commits!?? How this thing is supposed to work?

**Comment by jackhumbert** [comment]
Haha, reverting them leaves them in your history still - you can actually delete by hard resetting to that commit instead of reverting.

I'm open to moving things to unicode.c, but what's the point in keeping keymap_unicode.c?

There's currently [a branch](https://github.com/jackhumbert/qmk_firmware/tree/user_functions) that has 32bit keycodes with the full unicode support, but it's a bit out-dated.

**Comment by mecanogrh** [comment]
I must admit I hate github desktop or does it hate me? yup will save files and start from scratch, thanks for the good words :)
I left keymap_unicode.c here because... well... eheh... It better has to mutate and go to keymap/unicode/keymap.c I guess.

**Comment by jackhumbert** [comment]
Haha, it's not bad, just not designed to do fancy stuff like deleting 162 commits :)

I think we can drop the "keymap" terminology, and this file will likely get absorbed by the quantum.c file that's coming in the following weeks (in the leader-key branch).

**Comment by eltang** [comment]
@jackhumbert Do you want to see my implementation of the leader key? I decided to do it today and I'm halfway through it.

**Pull request closed without merging**
