### PR TITLE
adds support for GH60 Satan keyboard

### PR DESCRIPTION
**Pull request by TerryMathews**
ANSI 125 layout, capslock and backlight implemented, support for WS2812LED strip included
Also adds Satan and Phantom to travis config.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Just using up our pr/issue numbers :)

**Comment by TerryMathews** [comment]
Sorry, my skills in C greatly exceed my skills in GitHub. I'm going to have
to sit down and learn the ins and outs of it sometime.

**Comment by jackhumbert** [comment]
Haha, no worries. Thanks for submitting these! We might move `satan` into the gh60 eventually - I'm working on that subproject feature, which would be a good fit for that.

**Comment by TerryMathews** [comment]
That'll be nice, especially since there's something like 4 variations of
keymaps the Satan can support and 7 for the Phantom.

**Comment by jackhumbert** [comment]
I didn't even think about the layout variations - in the past we've just done those as `KEYMAP` macro shortcuts, but they get kind of complicated when there's more than one option.

**Pull request merged**
