### PR TITLE
Version 3, Ordinary Perfected

### PR DESCRIPTION
**Pull request by nrrkeene**
Hi Erez I spent some quality time with this layout and I think I made something special. It's a lot more complicated than it was before, or than the default is, but it allows all sorts of shifting between layers, and locking layers, in ways that are natural and complete. I worked with the LEDs a bit too. Cheers.

### CODE REVIEW

**Comment by ezuk** [comment]
I love it, @nrrkeene! So much thought put into this. I think I'll be featuring it as one of the notable community contributions on the new website. It's one of the more unique things I've seen labeled "ordinary" in a while ;)

**Comment by nrrkeene** [comment]
Thanks I appreciate the kind words. I wonder if anyone else uses this
layout? I spent a fair amount of time and iterations getting it right and I
think I basically have it now. There might be some tweaks, or some new keys
added to the Media layer, but I think I solved the hard part which was how
to deal with shifts and locks between layers. I find it very intuitive to
switch between layers now.

I had been eyeing the Ergodox for a long time but I don't solder so it
wasn't something I would buy. The EZ is a really good product which makes
the keyboard available to people like me, thank you. I'd be pickled if I
were featured on your website.

Nicholas

**Comment by ezuk** [comment]
Thank you, Nicholas! :)

**Comment by sboesebeck** [comment]
Hi Nicholas,

I really like the ideas of your layout, I am refining mine for quite some time now, also several iterations "in"... so I will take some of your ideas and incorporate them into mine.

Thanks a lot for thinking "out of the box" (at least out of my box!)

cheers,

Stephan

**Pull request merged**
