### PR TITLE
Add method to set Unicode input key for ISO 14755

### PR DESCRIPTION
**Pull request by coderkun**
See https://github.com/jackhumbert/qmk_firmware/issues/672

### CODE REVIEW

**Comment by algernon** [comment]
Is there any need to change the key at runtime? I'd suggest keeping only the define, and marking the `unicode_input_start` and `_stop` functions as weak, so keymaps can override them, and do their custom things, if so need be. This way, the code size does not increase, unless you really want to be able to change the key without reflashing.

Other than that, the patch looks fine to me, and the above is just my own opinion, and is not even a strong one.

**Comment by coderkun** [comment]
@algernon I agree that your suggestion sounds more reasonable and also more flexible if not only the key has to be changed. I am not familiar enough with C to implement this though.

**Comment by algernon** [comment]
It's actually very easy: drop `set_unicode_input_key_lnx`, and the `linux_key` variable, and use `UNICODE_LNX_KEY` in `unicode_input_start`. Then, change that function in the `.c` file so its firts few lines read:

```c
__attribute__((weak))
void unicode_input_start (void) {
```

That is, add the `__attribute__((weak))` line before it. And that should be it.

**Comment by coderkun** [comment]
Sounds easy, indeed. But is there any point in keeping `UNICODE_LNX_KEY` then?

**Comment by coderkun** [comment]
Done with commit 81594c7. Thanks @algernon!

**Comment by algernon** [comment]
There is some point in keeping it - one can redefine it in `config.h` of the keymap, and the code remains the same size, no run-time cost, and if all you want to do is replace the `KC_U`, that's lighter than having to replace the whole function. For all other purposes, when one may want to do more than change the U, there is the function override.

So its kind of the best of both approaches :)

**Comment by jackhumbert** [comment]
Cool - thanks! :)

**Pull request merged**
