### PR TITLE
Add ergodox_ez keymap to match Kinesis Contoured.

### PR DESCRIPTION
**Pull request by agriffis**
This keymap attempts to match the Kinesis Contoured (aka Advantage) default
layout as closely as possible. See
http://www.kinesis-ergo.com/wp-content/uploads/2013/06/advantage_layout_win.pdf

Apart from the obvious mappings, this keymap also:

* removes the dual-purpose momentary layer/normal keys: Z, /, and Grv;
  because the author--coming from a Kinesis keyboard--finds the delays and
  accidental modifiers to be more disconcerting than helpful.

* puts Esc in the bottom left since there's no place for it in the top
  left to match the Kinesis.

* changes the bottom-right key into an L2 toggle since there's otherwise no
  way to get to L2.

* adds PrScr, ScrLk and Pause to the L1 keymap, down the left side, since
  they're present on the Kinesis but not available in the default
  ergodox_ez keymap.

### CODE REVIEW

**Comment by agriffis** [comment]
This PR replaces #42

**Comment by ezuk** [comment]
@agriffis - looking great! Two thoughts:

1) It would be good if you could rename the file itself to `keymap_kines-ish.c` just to avoid any potential legal issues going down the road (trademarks etc.)

2) Could you grab the readme you wrote above and put it in `keymap_kines-ish_README.md` so that it remains available to all?

I'd do it myself but I see the PR comes from your own repo, so figured I'd ask. :) Love this! Thank you!

**Comment by ezuk** [comment]
@agriffis - I can also do (2) above myself if you want once you rename the file.

**Comment by agriffis** [comment]
@ezuk Should be all set now.

**Comment by ezuk** [comment]
@agriffis - Beautiful! Merged, thank you so much! :)

**Pull request merged**
