### PR TITLE
Beginner's keymap for Ergodox-EZ

### PR DESCRIPTION
**Pull request by abperiasamy**
It doesn't do justice to Ergodox-EZ's awesome powers, but it makes it accessible to common man.

### CODE REVIEW

**Comment by ezuk** [comment]
Nice! Any chance you could add a brief readme.md with a short description of the keymap and your thoughts about it?

**Comment by abperiasamy** [comment]
Sure Erez, will add readme.md and update this PR.

**Comment by abperiasamy** [comment]
Added readme.md

**Comment by ezuk** [comment]
Awesome! Thank you, merging! :)

**Pull request merged**
