### PR TITLE
pvinis keymap

### PR DESCRIPTION
**Pull request by pvinis**
my keymap :)
it has a base, qwerty, carpalx and a system control layer. also, using some tap dance.
will be improved over time.

### CODE REVIEW

**Comment by ezuk** [comment]
Thank you @pvinis! Any chance you could put together a quick readme describing the keymap?

**Comment by pvinis** [comment]
yes I wanna make a nice one. I will make a quick one on Monday when I'm back, and then update it progressively.

On Fri, Sep 23, 2016 at 03:39, Erez Zukerman <notifications@github.com> wrote:
Thank you @pvinis [https://github.com/pvinis] ! Any chance you could put together a quick readme describing the keymap?

**Comment by ezuk** [comment]
Thanks @pvinis! Standing by.

**Comment by pvinis** [comment]
I was fixing yesterday. I will push later today

On Tue, Sep 27, 2016 at 03:00, Erez Zukerman <notifications@github.com> wrote:
Thanks @pvinis [https://github.com/pvinis] ! Standing by.

**Comment by ezuk** [comment]
Sounds good @pvinis

**Comment by ezuk** [comment]
@pvinis closing this for now, please reopen once you push that readme. Thank you!

**Pull request closed without merging**
