### PR TITLE
Updated dbroqua layout for HHKB keyboard and added new layout for KC60

### PR DESCRIPTION
**Pull request by Dbroqua**
Hello,

I've recently updated my layout for the HHKB keyboard.

I've also added new layout for the KC60 keyboard by adding a HHKB like layout.

All is done.

Regards,
Damien

### CODE REVIEW

**Comment by Dbroqua** [comment]
I don't understand why checks fails :cry: .

**Comment by fredizzimo** [comment]
Don't worry it's not your fault. The cause for the failure is discussed [here](https://github.com/jackhumbert/qmk_firmware/pull/824). I don't have time to fix it yet, but I hope I have tomorrow.

**Comment by Dbroqua** [comment]
Hi @fredizzimo ,

Thank for your reply.

Damien

**Comment by jackhumbert** [comment]
Great! Thanks :)

**Pull request merged**
