### PR TITLE
Add KC_DQUO ("); update Zweihander

### PR DESCRIPTION
**Pull request by adiabatic**

### CODE REVIEW

**Comment by ezuk** [comment]
I love it! Thank you :)

**Comment by jackhumbert** [comment]
We already had `KC_DQT`, and this gives a warning for the redefinition. Adding it as an alias in a future commit.

**Comment by adiabatic** [comment]
I'd be happy to switch to KC_DQT myself — I just didn't see it mentioned in the expected places (`quantum/keymap_common.h` and `README.md`). This was about 100 commits ago; it must've been added while I was off in the woods on a separate branch and not paying attention to master on jackhumbert/qmk_firmware. Should we remove KC_DQUO since I'm the only one using it and I'd be happy to switch away?

**Comment by jackhumbert** [comment]
I actually prefer the `KC_DQUO` since it fits with the 4 letter shortnames - gotta keep DQT for now though too :)

**Pull request merged**
