### PR TITLE
Add Teensy2 Atreus support

### PR DESCRIPTION
**Pull request by seancaffery**
Add support for the Teensy2 hand-wired Atreus with the default layout.

/cc @technomancy

### CODE REVIEW

**Comment by jackhumbert** [comment]
Awesome! Thanks!

**Comment by technomancy** [comment]
Cool; thanks. Do you think you could add a note here that it only works with the older Teensy2 model just in order to avoid confusion among users of the newer A-Star model?

**Comment by gerbercj** [comment]
@seancaffery: I'm currently have my A-Star Atreus running with a commit on top of the SHA just prior to this. If I try to merge our worlds, could you test compatibility with the Teensy2?

/cc @jackhumbert @technomancy

**Comment by seancaffery** [comment]
Yep, I'll take a look when you're ready :smile_cat:

**Comment by gerbercj** [comment]
I really appreciate that... I'll try to get something reasonable together over the next couple of days.

**Pull request merged**
