### PR TITLE
Fix the makefile dependencies and remove quick targets

### PR DESCRIPTION
**Pull request by fredizzimo**
Proper clean targets have also been added.

As a note, in order to use the `QMK_VERSION`, and `QMK_BUILDDATE` macros, you need to include `version.h`

This pull request builds on top of #595, so if this one passes the Travis build, I will close that one.

### CODE REVIEW

**Comment by fredizzimo** [comment]
The compilation speed of this one was quite a bit faster than #595. But it was still slower than normal.

**Comment by fredizzimo** [comment]
I think there might be something wrong with the dependency checking. If I run make all-keyboards, and then make a single keyboard that was already compiled, it will do a re-compile. 

The same thing happens the other way too. However if I run the same command to compile a single keyboard again, it won't recompile.

**Comment by fredizzimo** [comment]
It's nothing serious. 

Depending on which way you invoke make, the working directory will be different, and therefore the paths. Which turns into different include path compiler flags. Therefore causing re-compilation.

It's not a serious issue, as it just re-compiles instead of doing nothing. So at least it's correct.

Therefore I won't fix this as a part of this pull request. But instead when I overhaul the whole top-level rule processing logic.

**Comment by jackhumbert** [comment]
Awesome :)

**Pull request merged**
