### PR TITLE
Restructure documentation

### PR DESCRIPTION
**Pull request by NoahAndrews**
Don't merge this yet. This is just a jumping off point.

### CODE REVIEW

**Comment by NoahAndrews** [comment]
@jackhumbert Are you sure that the Mac instructions provided are correct? Do the Xcode command line tools include an AVR compiler?

**Comment by jackhumbert** [comment]
I'm pretty sure the homebrew ones are - those are the ones I wanna try to stick to/promote for now. I do believe XCT contains the AVR compiler.

**Comment by NoahAndrews** [comment]
I'll clarify that that's the recommended method, and provide a link to install homebrew.

**Comment by ezuk** [comment]
@NoahAndrews looks like you got this all done! :) My weeks are just insane, Friday night and I only managed to get to this now. Thank you!!

**Comment by NoahAndrews** [comment]
Well, it's not exactly finished. I daresay it got merged a bit prematurely. We'll get it completed though!

**Comment by ezuk** [comment]
One thing I'm wondering about it why we all-cap the filenames. Feels like the files are SHOUTING at me, kind of stressful :)

**Comment by NoahAndrews** [comment]
That's a pretty standard convention for GitHub repos though.

**Comment by NoahAndrews** [comment]
I feel like it's how you say "These files are documentation, not source code".

**Comment by ezuk** [comment]
Interesting -- in the Rails world (where I come from) it's usually just "
readme.md". Same for vim plugins quite often. Oh well, no biggie :)

**Pull request merged**
