### PR TITLE
makefile TARGET is KEYMAP name

### PR DESCRIPTION
**Pull request by VoodaGod**
instead of building the planck firmware hex with the same default name every time, the hex uses the keymap's name as filename, so multiple different firmwares can be built without overwriting each other.

### CODE REVIEW

**Comment by jackhumbert** [comment]
I'm still pretty torn on this - I like the keyboard name being in the target's filename. Maybe we could do PROJECT_KEYMAP?

Ideally, the .hex file would have the same name across all projects, eg `firmware.hex`.

**Comment by VoodaGod** [comment]
is this what you mean?

keyboard name: planck
keymap name: myKeymap

would result in 
planck_myKeymap.hex

**Comment by jackhumbert** [comment]
Yeap! It'd also be neat to stick it in the respective keymap folder as well, like the EZ does it.

**Comment by VoodaGod** [comment]
This took me way longer to figure out than I expected, but at least I now know the basics of make ;D
I've tested this with default & multiple keymaps for the planck and the untouched preonic makefile, and observed no problems.
Is there any way to not have to have the extra "mkdir" command in rules.mk?

**Comment by VoodaGod** [comment]
any suggestions?

**Comment by ezuk** [comment]
@jackhumbert what say you? @VoodaGod no suggestions from me, I just want to either get this working or close ;)

**Comment by jackhumbert** [comment]
A version of this was implemented in #395 - sorry I couldn't merge this properly, but thanks for doing that!

**Pull request closed without merging**
