### PR TITLE
Add scripts for easy Windows environment setup

### PR DESCRIPTION
**Pull request by NoahAndrews**
Currently tested on Windows 10, 64-bit.

### CODE REVIEW

**Comment by NoahAndrews** [comment]
The reason I recommend the MHV AVR tools instead of the official ones is that they're much easier to obtain. With the official ones, you have to give them your email address and have a link emailed to you. The MHV AVR Tools work perfectly even on the latest version of Windows, and even allow for redistribution if we want to go that route.

**Comment by ezuk** [comment]
This looks good to me! Perhaps consider moving the readme to something like the QUICK-START.md in the root? Maybe we can refactor that file, change it to "build_instructions.md" and include both your doc and the existing content?

**Comment by NoahAndrews** [comment]
I couldn’t agree more that files need to be shuffled around, and that’s what I’m going to work on next. I’m thinking about renaming the quick start file to VAGRANT-SETUP.md.

**Comment by ezuk** [comment]
It would be cool if there was just a single build document, split up into
various OSes and what you need to do to get set up with each. What do you
think? Happy to collaborate on something like that.

**Comment by NoahAndrews** [comment]
Agreed! And that should go in the root, not in the Planck folder.

**Comment by ezuk** [comment]
Totally. And be linked from the main project readme. Wanna get it started?

**Comment by NoahAndrews** [comment]
You make the Ergodox EZ, right? Does that disqualify you from [this](https://www.reddit.com/r/olkb/comments/47mmxf/free_planck_pcb_for_documentation_cleanup/)? :P

**Comment by NoahAndrews** [comment]
When I get home from this robotics meeting, yeah!

**Comment by ezuk** [comment]
Hahaha, yeah, I make the ErgoDox EZ :) What I say in the video is the truth
-- I'm really not into soldering, I just bought my Planck all assembled
from @jackhumbert. :)

**Comment by NoahAndrews** [comment]
I've created a separate pull request for the restructuring https://github.com/jackhumbert/qmk_firmware/pull/171

**Comment by NoahAndrews** [comment]
Have you actually tested my new build instructions and script? It would be good to have confirmation that it works somewhere other than my test VM.

**Comment by NoahAndrews** [comment]
I've added you as a contributor to my fork so that you can contribute to that branch.

**Comment by jackhumbert** [comment]
This is great! :)

**Pull request merged**
