### PR TITLE
Add support for Atreus running on A-Star

### PR DESCRIPTION
**Pull request by gerbercj**
This pull request is to add support for A-Star based Atreus keyboards, in addition to the existing support for the Teensy 2 based version. It also includes the following:
 * support for `make upload`, like in [atreus-firmware](https://github.com/technomancy/atreus-firmware)
 * my personal keymap

When targeting an A-Star, add `ASTAR=yes` to your `make` commands.

@seancaffery
/cc @jackhumbert @technomancy

### CODE REVIEW

**Comment by technomancy** [comment]
Thanks. Personally I think it would make sense to make the A-Star the default since the Teensy is only used in the legacy design, but as this is not my codebase I will just leave that as a suggestion.

**Comment by gerbercj** [comment]
@technomancy: I was going to make A-Star the default, but didn't want to break @seancaffery's build (yet). Given that all future Atreus keyboards **should** be A-Star based, I agree that having that default would be the least surprising... especially for new users.

**Comment by jackhumbert** [comment]
Let's go with A-Star being the default - building with Teensy will be something like `TEENSY=yes`, right? @seancaffery, you'll need to add this to you `make` commands, or modify things on your personal fork to your liking :)

**Comment by gerbercj** [comment]
Sounds like a plan. I'll rework my changes tonight.

**Comment by gerbercj** [comment]
@technomancy @jackhumbert @seancaffery:
I changed the default to A-Star. Now you need to use TEENSY2=yes to override that. Any other questions or concerns?

**Comment by technomancy** [comment]
Sounds good to me; thanks!

**Comment by jackhumbert** [comment]
Awesome - thanks!

**Pull request merged**
