### PR TITLE
Some updates for GH60 and Satan keyboard

### PR DESCRIPTION
**Pull request by Dbroqua**
Rewrote my layouts for GH60 and Satan keyboards.

Added RGB Light on dbroqua satan.

### CODE REVIEW

**Comment by Dbroqua** [comment]
Hello,

Don't pull my request please. With the Satan layout I have a mistake. My layout is always on _FN layer (or _SFX) but never on the default layer :( .

If you have any idea...

Regards,
DarKou

**Comment by Dbroqua** [comment]
In fact it's because my keyboard stored layer 1 as default layer.

How to reset this ?

Regards,
DarKou

**Comment by Dbroqua** [comment]
All change done ^^.

Merry chistmas for all mechanical keyboard's addict :D .

**Comment by jackhumbert** [comment]
Awesome - thanks :)

**Pull request merged**
