### PR TITLE
PS/2 mouse support

### PR DESCRIPTION
**Pull request by OferPlesser**
This brings back support for PS/2 devices from tmk.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Awesome! Thanks :)

**Comment by daniel-sousa-me** [comment]
I just ordered an Ergodox EZ and bought a broken Thinkpad T400 to try to connect its Trackpoint on the Ergodox.
I have trying to find information online on how to do that, but there are some questions I haven't been able to figure out.

According to the wiki, I should connect PD5 to clock and PD2 to data (I am assuming these will be available).
It doesn't say anything about VCC and GND, but I guess I would have to connect those. Where and how?

Do I need to add connect buttons to the Trackpoint or can the mouse  buttons be emulated from the keyboard?
Some people talk about some complicated circuit for the reset pin? Is this necessary? Will I need to connect the pin somewhere?

**Comment by ofples** [comment]
I haven't got any experience with Thinkpad trackpoints but the vcc and gnd need to be connected to the +5v and gnd pins respectively.
Good luck :)

**Comment by aizigao** [comment]
how to  link trackpointer

**Comment by priyadi** [comment]
The canonical source of Trackpoint wiring information is currently the [Trackpoint Hardware](https://deskthority.net/wiki/TrackPoint_Hardware) page on Deskthority Wiki. I've added the information to QMK wiki.

**Comment by aizigao** [comment]
great, thx

**Comment by priyadi** [comment]
@daniel-sousa-me 

> According to the wiki, I should connect PD5 to clock and PD2 to data (I am assuming these will be available).
> It doesn't say anything about VCC and GND, but I guess I would have to connect those. Where and how?

To VCC and GND of the controller. They should be marked as such very clearly.

> Do I need to add connect buttons to the Trackpoint or can the mouse buttons be emulated from the keyboard?

I think it can be emulated. But I don't recommend it. Middle button scrolling is handled by the Trackpoint hardware and requires middle button to be connected to the module. Offloading middle button to the controller will of course disable this important feature.

> Some people talk about some complicated circuit for the reset pin? Is this necessary? Will I need to connect the pin somewhere?

It is not that complicated. Please see the [Trackpoint Hardware](https://deskthority.net/wiki/TrackPoint_Hardware) page on Deskthority for more details.

**Pull request merged**
