### PR TITLE
Add variants of layouts in directory

### PR DESCRIPTION
**Pull request by xaocon**

### CODE REVIEW

**Comment by ezuk** [comment]
Thanks @xaocon -- but I must admit I'm not completely sold on the idea. A big part of the motivation for subdirs was making things discoverable for novice/non-technical users.

That's why I encourage people to include their hex files; and that's why each directory should ideally have its own readme.md.

As a novice user, I should be able to just scan the keymaps directory on GitHub and intuitively understand that this is what I've got -- each subdir represents a possible keymap for my keyboard. I find that simplicity compelling, and I'm not sure there's reason to nest variants and essentially hide them away. 

I know we'll get more directories this way, but I'm not convinced this is a bad thing. What do you think?

**Comment by jackhumbert** [comment]
I think this is probably fine, but my concern is it taking the focus away from the folders. In the future (and what will be the case with other Quantum projects soon), there will be a standardised file structure inside these folders, and allowing more than one keymap per folder breaks this mindset.

I can see it being really useful for dvorak/colemak alternatives (for hard-coding those layouts), but I think there may be better(?) alternatives.

Either way, I think `keymap_$(VARIANT).c` would be preferred, to prevent confusion. It's possible (while maybe not the best idea) that people will be adding their own libraries/.c files to these folders.

**Comment by xaocon** [comment]
I think that's perfectly reasonable. I feel like a novice would need a lot of direction to find the README's and use the included hex files so it didn't seem like a stretch for them to pick the hex file they wanted from the README. It could be used for cases like default and default_osx since they have so much overlap anyways. You've been dealing with all the new users though so you have a better grasp on how they will be using it than me. If you can use it, feel free to, if not, no hard feelings of course.

**Comment by xaocon** [comment]
If my changes will break the file structure that will be used down the line then you should just close this. I just thought there would be a lot of cases for 1 off variants like specific OS's, dvorak/colemak, right vs left handed, etc.

**Comment by xaocon** [comment]
If you decide you want to use it but want the naming change just let me know and I'll add another commit to it.

**Comment by ezuk** [comment]
For now, I'd like to close this one, but definitely keeping the idea for future consideration. Thanks @xaocon!

**Pull request closed without merging**
