### PR TITLE
Add my layout optimized for working in emacs, vim, command line, etc.

### PR DESCRIPTION
**Pull request by mazinbokhari**

### CODE REVIEW

**Comment by ezuk** [comment]
@mazinbokhari - I love this keymap! My only comment would be, could you please remove the default PNGs? They might confuse some people :) Once done, I'll merge right away!

**Comment by mazinbokhari** [comment]
Agreed. Wanted to say thanks again for making a great quality product!

**Comment by ezuk** [comment]
Thank you!! :) Merging!

**Comment by jackhumbert** [comment]
This needs to be updated to the new `keyboards` :/

**Comment by mazinbokhari** [comment]
sorry about that: #564

**Pull request merged**
