### PR TITLE
Connect the adafruit ble code to the lufa main loop

### PR DESCRIPTION
**Pull request by wez**
(this is part of a series relating to #912; it is stacked on top of #915, so there are apparently duplicate commits here due to the lack of stacked diff review support on GH)

There are now 3 potential locations to send HID reports:

1. USB
2. The bluefruit easy key
3. Adafruit BLE

Generally speaking, if USB is connected then we should prefer to
send the reports there; it is generally the best channel for this.

The bluefruit module has no feedback about bluetooth connectivity
so the code must speculatively send reports over both USB and bluetooth.

The BLE module has connectivity feedback.  In general we want to
prefer to send HID reports over USB while connected there, even
if BLE is connected.  Except that it is convenient to force them
over BLE while testing the implementation.

This policy has been extracted out into a where_to_send function
which returns a bitmask of which of the channels should be used.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Awesome - it looks like there's a conflict with lufa.c from where we pulled in #918. If you could pull those changes that would be great!

**Comment by wez** [comment]
Resolved and updated!

**Comment by jackhumbert** [comment]
Perfect! Thanks :)

**Comment by harshitgoel96** [comment]
Hi,

I have reported 2 issues with Adafruit Feather 32u4 in #2229 can you please help

**Pull request merged**
