### PR TITLE
pvinis keymap

### PR DESCRIPTION
**Pull request by pvinis**
this time with readme.

### CODE REVIEW

**Comment by ezuk** [comment]
@pvinis I love it! Thank you, merging!

**Comment by algernon** [comment]
Quick question about this keymap, @pvinis: does the flash button put the keyboard into a flashable state? As in, can I flash the keyboard without having to press the hidden reset button on it?

**Comment by pvinis** [comment]
yes, i tap 4 times the flash key, and the keyboard gets in the flashable state, so the teensy app autoflashes it. the only other way i know that can flash the keyboard is if you press the tiny button with a pin or something, on the top right of the keyboard. how do you flash it?

**Comment by DidierLoiseau** [comment]
@algernon @pvinis Well, you can simply put a `RESET` key in some layer, it will trigger the flashing on press.

I have been [using that for months now in my FN layer](https://github.com/jackhumbert/qmk_firmware/blob/0a9ad8f335f5b5b9d184d9e5e9ece6cda149df7e/keyboards/ergodox/keymaps/bepo_csa/keymap.c#L344) and never had an issue, except it does not work anymore after you use the Teensy button (see #164): you need to unplug the keyboard to make it work again. Not really a problem if you only use the `RESET` key.

**Comment by pvinis** [comment]
well yea a normal button on some layer would work. but I wanted it always available in all layers, just harder than 1 press. tap dance was great for that. also I get a light show :)

On Thu, Oct 13, 2016 at 13:44, DidierLoiseau <notifications@github.com> wrote:
@algernon [https://github.com/algernon] @pvinis [https://github.com/pvinis] Well, you can simply put a RESET key in some layer, it will trigger the flashing on press.

I have been using that for months now in my FN layer [https://github.com/jackhumbert/qmk_firmware/blob/0a9ad8f335f5b5b9d184d9e5e9ece6cda149df7e/keyboards/ergodox/keymaps/bepo_csa/keymap.c#L344] and never had an issue, except it does not work anymore after you use the Teensy button (see #164 [https://github.com/jackhumbert/qmk_firmware/issues/164] ): you need to unplug the keyboard to make it work again. Not really a problem if you only use the RESET key.

**Comment by algernon** [comment]
Hrm. I've had problems with `RESET` in the past... will give it another try. Thank, both of you!

**Comment by pvinis** [comment]
what kind of problems? just not getting in in flash-mode?

**Comment by algernon** [comment]
Yeah.

**Comment by pvinis** [comment]
hm, i havent had anything like that. try it and if you see something broken, report back :)

**Comment by algernon** [comment]
Played with `RESET` today, and it turns out that it works well, it was the Teensy Loader GUI that did not notice the device being in flash mode. I switched to `teensy_loader_cli`, and automated the whole thing, so I don't even need the loader gui running in auto mode.

Thank @pvinis for the idea! Now I have a comfy reset button too :)

**Comment by pvinis** [comment]
awesome :)
how do you generate the images?

**Comment by algernon** [comment]
Click them :)

I use [KLE](http://www.keyboard-layout-editor.com/), which has a "Download PNG" option. Clicking on the images in the README of my keymap should take you to the KLE page with the layer pre-loaded.

**Comment by pvinis** [comment]
oh oops. didnt notice the link. cool, thanks!

**Pull request merged**
