### PR TITLE
Cleans up quantum/keymap situation, removes extra lufa folders

### PR DESCRIPTION
**Pull request by jackhumbert**
Pulls some ideas from #396

### CODE REVIEW

**Comment by eltang** [comment]
After looking a bit more at the Quantum, I realized that things are more complicated than I thought (read: you were right to not merge #396). It's going to take a bit more work to disambiguate TMK action codes and Quantum keycodes enough so that they can both be put into keymaps at compile time. Perhaps the expansion to 32-bit keymaps will help.

**Comment by jackhumbert** [comment]
That's really not necessary, and not a goal right now. 32bit keycodes (if we even decide to use them) are pretty far off right now as well.

**Comment by eltang** [comment]
It just seems a little silly to me that the whole purpose of certain Quantum keycodes is to be converted to TMK action codes on the fly, especially since they don't take up any less space. It would just be a lot simpler to store the action codes directly. I didn't know that 32-bit keycodes were still under consideration, though.

**Comment by jackhumbert** [comment]
The current action mappings will eventually be implemented natively with the quantum stuff.

**Comment by eltang** [comment]
I'm looking forward to seeing that!

**Pull request merged**
