### PR TITLE
fix ergodox ez link

### PR DESCRIPTION
**Pull request by nclundsten**

### CODE REVIEW

**Comment by nclundsten** [comment]
nevermind, the link that was broken was on qmk.fm, not in the repo.

**Comment by fredizzimo** [comment]
@nclundsten, @ezuk, @jackhumbert  Can you re-open this pull request. The link is still broken, and the qmk.fm is automatically generated, so this should fix it.

**Comment by jackhumbert** [comment]
Thanks :)

**Comment by fredizzimo** [comment]
@jackhumbert, @ezuk  For some strange reason the link here http://qmk.fm/#included-keyboards, is still not updated. Do you have any idea why?

**Comment by nclundsten** [comment]
Its possible that page is reading a local version that isnt updated, or its
pointing to a certain commit hash/etc, depending on how its set up

**Comment by fredizzimo** [comment]
I wont have time to check further, but I saw this in the travis logs

> pandoc: Cannot decode byte '\xb4': Data.Text.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream

Which probably means that we have some invalid characters in the readme.md, and the format is not UTF-8. Pandoc accepts only valid UTF-8.

**Comment by fredizzimo** [comment]
It seems to work now. I guess the invalid UTF-8 character might have come from the typo that was fixed in #685.

**Pull request merged**
