### PR TITLE
Add ChibiOS packages to the avr_setup script

### PR DESCRIPTION
**Pull request by fredizzimo**

### CODE REVIEW

**Comment by jackhumbert** [comment]
Nice - should we name this to something besides `avr_setup`, though?

**Comment by fredizzimo** [comment]
Probably yes, I had the same thought, but decided to leave it like this for now, since I don't know the consequences of renaming it. And of course we also need a good name, maybe install_dependencies?

At least the Vagrant file needs to be updated, and probably some of the documentation.

**Comment by jackhumbert** [comment]
Yeah, I think it's just the Vagrantfile - my search didn't pull up anything in the readmes :) feel free to change that! `install_dependencies` sounds good!

**Comment by fredizzimo** [comment]
Ok, I have done the renaming.

I also added Git as a dependency, since the version generation needs it, and so do my submodule check, that I have in another pull request.

I also changed cd keyboard to cd keyboards in the Vagrant message.

**Comment by jackhumbert** [comment]
Nice - thanks!

**Pull request merged**
