### PR TITLE
Support the Pegasus Hoof controller.

### PR DESCRIPTION
**Pull request by dsvensson**
Been using this for the past 6 months and it works really well, a pair of extra eyes would be nice though.

### CODE REVIEW

**Comment by dsvensson** [comment]
Any idea why that failed? Doesn't clash with any files I touched?

**Comment by dsvensson** [comment]
Wonder if it's -ETOOMANYKEYBOARDCONTROLLERS, I get this when I run the all-keyboards build locally:

    make TARGET=all-keyboards AUTOGEN=true
    keyboards/jd40/Makefile:72: ../../Makefile: No such file or directory
    make: execvp: /bin/sh: Argument list too long
    Makefile:474: recipe for target 'allkb-allsp-allkm' failed
    make: *** [allkb-allsp-allkm] Error 127

**Comment by pvinis** [comment]
looking online a bit, i saw that there should be a `for` or `foreach`.
[here](http://stackoverflow.com/questions/11475221/why-do-i-get-bin-sh-argument-list-too-long-when-passing-quoted-arguments) and [here](https://bbs.archlinux.org/viewtopic.php?id=160495)

**Comment by fredizzimo** [comment]
I'm not sure, but I don't think its related to your pull request. The master gives the same error, but doesn't fail the build. 

All I know is that the JD40 is needs to be slightly updated to follow the new makefile structure, so the error is real. 

I dont have time to investigate more right now, but I definitely will, we need to get reliable error detection in travis.

**Comment by fredizzimo** [comment]
I didn't see the other error before. But it seem like your keyboard made the commandline for compiling them too long. It's not caused by this pull request directly, but by the total number of keyboards and keymaps.

At least that's my best guess right now, without having access to the code, and after a few glasses of wine, so I might be completely mistaken. I might have a chance to take a proper look during the weekend, but I'm can't promise anything. So if someone else have more time, feel free to fix it.

**Comment by dsvensson** [comment]
@fredizzimo yep, that was what I gathered as well. Sorry to drag you in to this, I was hoping your reply would be "ofc, it's due to this" as I know you did some work on rearranging the build system recently. I'll try to find the time to dig into how the build system works myself as well unless someone else gets the urge to add another keyboard before me :). Thanks for your comments.

**Comment by jackhumbert** [comment]
Awesome - thanks!

**Pull request merged**
