### PR TITLE
- Updated dbroqua layout for planck keyboard

### PR DESCRIPTION
**Pull request by Dbroqua**

### CODE REVIEW

**Comment by jackhumbert** [comment]
It looks like there are some conflicts here - would you mind pulling the updates from master?

**Comment by Dbroqua** [comment]
Hello,

I want update my previous layout with the last updates.

Regards,
Damien

**Comment by Xyverz** [comment]
@Dbroqua - looks like you need to do [sync your fork](https://help.github.com/articles/syncing-a-fork/) before this pull request can be accepted.

**Comment by Dbroqua** [comment]
@Xyverz  thanks !

I'm a newbie with git tools ^_^

**Comment by Xyverz** [comment]
Just passing on what I'd learned two weeks ago. :-)

**Comment by Dbroqua** [comment]
:-)

**Comment by Dbroqua** [comment]
Hello,

How to push my modifications on this master and close this pull ?

**Comment by Xyverz** [comment]
Any changes you push back to your fork before the pull request has been
merged will be added into the upstream/master when Jack finally merges this
pull request.

**Comment by Dbroqua** [comment]
Hello @Xyverz , thanks for your response :-)

**Comment by fredizzimo** [comment]
Jack merged it already, but I had already typed this...
@Dbroqua, I can't tell for sure, but I guess, @jackhumbert  is waiting with the merge to the master, because you are adding new things all the time, so its hard to tell when you consider it stable enough.

I know that you are new with GIT, but the usual way to both push pull request and continue with your own development, is to use feature branches, and submit a pull request when you consider it done. However I don't recommend this is you are not comfortable with GIT, and I can't find any simple tutorials by doing a quick Google search. 

We should probably write our own documentation here about how to easily work with GIT for different situations,  especially since many people here are absolute beginners with that.

**Comment by Dbroqua** [comment]
Hello @fredizzimo ,

Thanks for your explanations. 

I'm never satisfied by my work and I can't stop commit after each improvement of my code :D .

I will try to push less for push only final work ^^.

Regards,
dbroqua

**Pull request merged**
