### PR TITLE
Addressing void* return warning & coding style

### PR DESCRIPTION
**Pull request by yoyoerx**
This is a change that eliminates a warning generated during the make process and cleans up the code a little.  

The problem was raised [here by /u/cdlm42](https://www.reddit.com/r/olkb/comments/46wuof/confused_with_details_in_qmk_coding_style/).  It seems that there was a design feature to have the possibility of a `null` function pointer so it could skip the function call.  It does not seem like it was implemented correctly as the pointer is never `null`.  It always points to either a local function or an external function.  It also looks like it has been abandoned as a feature in `tmk`.

As this changes the function prototypes, it has the possibility to break keymaps that have `matrix_init_user` and `matrix_scan_user` implementations.  The easy solution is to change the declarations in their maps from 
```
void * matrix_scan_user(void) {

}
```
to

```
void matrix_scan_user(void) {

}
```

I have done this for the template, Plank, and Atomic. (The Preonic did not implement this feature).

### CODE REVIEW

**Comment by jackhumbert** [comment]
Awesome! Thanks for doing that :) I believe the Ergodox EZ uses these functions as well - @ezuk do these changes work for you?

**Comment by DidierLoiseau** [comment]
This change will break the build of all keymaps that were not changed yet:

```
Compiling C: keymaps/bepo/keymap.c
avr-gcc -c -mmcu=atmega32u4 -gdwarf-2 -DF_CPU=16000000UL -DINTERRUPT_CONTROL_ENDPOINT -DBOOTLOADER_SIZE=512 -DF_USB=16000000UL -DARCH=ARCH_AVR8 -DUSB_DEVICE_ONLY -DUSE_FLASH_DESCRIPTORS -DUSE_STATIC_OPTIONS="(USB_DEVICE_OPT_FULLSPEED | USB_OPT_REG_ENABLED | USB_OPT_AUTO_PLL)" -DFIXED_CONTROL_ENDPOINT_SIZE=8  -DFIXED_NUM_CONFIGURATIONS=1 -DPROTOCOL_LUFA -DBOOTMAGIC_ENABLE -DMOUSEKEY_ENABLE -DMOUSE_ENABLE -DEXTRAKEY_ENABLE -DNO_PRINT -DNO_DEBUG -DCOMMAND_ENABLE -DNKRO_ENABLE -DSLEEP_LED_ENABLE -DNO_SUSPEND_POWER_DOWN -DVERSION=ef58316-dirty -Os -funsigned-char -funsigned-bitfields -ffunction-sections -fdata-sections -fno-inline-small-functions -fpack-struct -fshort-enums -fno-strict-aliasing -Wall -Wstrict-prototypes -Wa,-adhlns=obj_ergodox_ez/keymaps/bepo/keymap.lst -I. -I../.. -I../../tmk_core -I../../quantum -I../../tmk_core/protocol/lufa -I../../tmk_core/protocol/lufa/LUFA-git -I../../tmk_core/common -std=gnu99 -include config.h -MMD -MP -MF .dep/obj_ergodox_ez_keymaps_bepo_keymap.o.d  keymaps/bepo/keymap.c -o obj_ergodox_ez/keymaps/bepo/keymap.o 
keymaps/bepo/keymap.c:501:8: error: conflicting types for ‘matrix_scan_user’
../../tmk_core/rules.mk:551: recipe for target 'obj_ergodox_ez/keymaps/bepo/keymap.o' failed
 void * matrix_scan_user(void) {
        ^
In file included from keymaps/bepo/keymap.c:2:0:
./ergodox_ez.h:127:6: note: previous declaration of ‘matrix_scan_user’ was here
 void matrix_scan_user(void);
      ^
make: *** [obj_ergodox_ez/keymaps/bepo/keymap.o] Error 1
```

Maybe there should be a smoother path? Something like declaring new functions to implement, but calling the old ones if the new ones aren't there?

**Comment by yoyoerx** [comment]
@DidierLoiseau, you are correct.  All keymaps that use matrix_scan_user() would need to be changed for this to work.

I could put out a new pull request with the prototype as `void * matrix_scan_user(void) __attribute__ ((deprecated));` and then create a new standard `void matrix_scan_user_new(void);`; we could then work to phase out the deprecated function over time. The downside to this is that it creates additional function calls in `matrix_scan()` rather than simplifying them.

Any input on the new name? C is not polymorphic, so we cannot have the same name for the function.

**Comment by ezuk** [comment]
Yeah, I would really rather not having a change that breaks the community contributions... As I understand it, the benefit here is a cleaner build process, which is cool -- but I am not sure it's worth breaking a bunch of layouts for that. :)

**Comment by ezuk** [comment]
And thanks as ever to @DidierLoiseau for keeping an eye out!!

**Comment by yoyoerx** [comment]
@ezuk understood. I will see about using the depreciation tag to make a smoother transition.

**Comment by jackhumbert** [comment]
I would rather just have all the keymaps updated at once in this PR - if someone pulls without updating their functions, it should be fairly trivial to remove the `*`, right?

This is definitely my fault for not knowing what I was doing when writing the functions :)

**Comment by yoyoerx** [comment]
It should be easy, but I hate the idea of annoying everyone.

I can go through all the included keymaps and change it with just a well crafted regex.  It would still be an issue for keymaps outside this repo, though.

**Comment by yoyoerx** [comment]
I have checked compilation of all the ergodox_ez keymaps .  All compiled without error.  I don't have an ergodox, so I cannot verify that they run. 

I would recommend test flashing a few of the builds to be certain.

**Comment by DidierLoiseau** [comment]
> I can go through all the included keymaps and change it with just a well crafted regex. It would still be an issue for keymaps outside this repo, though.

I think changing the keymaps that are already in this repo is not really an issue, the problem is more for people pulling from here: this change will break their build.

Even if the fix might look easy, we could see people create issues here because they don't understand what's going on.

Also, should .hex files be updated too?

**Comment by ezuk** [comment]
I think changing the hex files would be good, yes. And breaking upstream changes happen sometimes -- people will just pull again and we should be good I think.

**Comment by yoyoerx** [comment]
I can make the hex tomorrow. I could also make a bash script that would sed the offending *.  We could refer people to the "hotfix.sh" if they cannot handle it themselves.

**Comment by yoyoerx** [comment]
I have rebuilt all the hex files(added a script to do this, makeallhex.sh).  Please test a few of the hex files before committing to make sure there are no build issues.

I noted that the tm2030 hex did not follow the naming convention, so I fixed it.

I have also added a script 190hotfix.sh which should automagically convert the function definitions in a keymap to the new style. i.e., `./190hotfix.sh bepo` should update your keymap, @DidierLoiseau.

What do we think? Is this PR ready?

**Comment by ezuk** [comment]
I just tested a bunch of these on my ErgoDox EZ, and I feel good about merging this in. @jackhumbert what do you think?

@yoyoerx thank you for all the hard work on this! Awesome PR, love the build script too.

**Comment by yoyoerx** [comment]
Is this dead? Do we need any additional modifications? or are we just waiting for the right time?

**Comment by ezuk** [comment]
@yoyoerx - I have no idea what we're waiting for... imho we waited too long... this now has merge conflicts. Would you be okay with resolving and pinging again, and I'll merge right away? No input from @jackhumbert but can always revert ;)

**Comment by jackhumbert** [comment]
Sorry for the radio silence - fine by me to merge once conflicts are resolved!

**Comment by ezuk** [comment]
Thanks Jack!

**Comment by yoyoerx** [comment]
@ezuk, conflicts resolved.  Merge when ready.

**Comment by ezuk** [comment]
Yay! Merged, thank you!

**Comment by cdlm** [comment]
:+1: thanks for taking the time to look into this!

**Pull request merged**
