### PR TITLE
Added Error Checking to 2nd Setup Script

### PR DESCRIPTION
**Pull request by IBNobody**
Added check for the MinGW directory. Fixed a bug with script exiting out of a CMD window. Fixed a bug with script dropping user into MinGW directory. Fixed a bug with RD not deleting temp. Fixed a bug with PNPUtil.exe not being present in the path.

### CODE REVIEW

**Comment by NoahAndrews** [comment]
Nice! Eventually we should also add error-checking for mingw-get if possible. I've already talked to one person who had that step fail.

**Comment by IBNobody** [comment]
Hmm... What do you propose? IF EXIST for wget and IF EXIST for unzip? Then if needed run mingw-get and error check that?

Also, what are your thoughts on adding make_qmk.bat and make_clean.bat to the template? Maybe add a make_special.bat with user prompts for the make recipes and keymaps?

**Comment by NoahAndrews** [comment]
That sounds like a good idea.

Hmm, interesting. I like it. I think it would be best to write them as BASH scripts which the bat files just call, that way Linux and Mac users can avoid the command prompt as well, if they so choose. The current setup script actually installs the BASH shell as a dependency.

Here's how I envision the flow going. The first time you run make_qmk it asks you to set a default keymap. You type in the name of a keymap and it creates a file called default_keymap.txt with that name in it (assuming the keymap existed). The user would be informed that they can change the default keymap by editing that file. The rest of this run and all future runs consist of making the hex file, and then prompting the user if they want to flash it or not. They would be given a few seconds to put their keyboard in reset mode. Then there would be a make_other script that would prompt the user for which keymap to make/flash. The simplest way to handle Teensy-based keyboards is to tell the user in the "do you want to flash" prompt that they should say no if they are using a Teensy, and point them to the Teensy Loader.

We'd also need to add a line to .gitignore for the default_keymap.txt files.

**Comment by IBNobody** [comment]
Ok. We can do that. But... I don't want to fill the template with 6 files. Also, I wouldn't want to maintain complex scripts in every keyboard folder. 

What if we created some batch/shell script combo files that could run from bash and CMD.EXE?

See this [StackOverflow](http://stackoverflow.com/questions/17510688/single-script-to-run-in-both-windows-batch-and-linux-bash) question. I did some trials with it in Win7 and Linux and had positive results.

**test.sh.bat**
```
: # This is a special script which intermixes both sh
: # and cmd code. It is written this way because it is
: # used in system() shell-outs directly in otherwise
: # portable code. See http://stackoverflow.com/questions/17510688
: # for details.
:; ./sample.sh ${PWD#*/} $*; exit
@ECHO OFF
bash sample.sh %cd% %*
```

**sample.sh**
`echo "This is ${SHELL}, the file is $0, and the commandline is $*"`

The idea would be that we'd have a file called `make_qmk.sh.bat` (and maybe a few others) in the template folder. This file would call `master_make_qmk.sh` from a new base scripts folder in `qmk_firmware`. That way, we could have complex .sh scripts that can do everything you mentioned with 3 extremely simple and double-clickable scripts in the template.

**Comment by NoahAndrews** [comment]
I still haven't decided what I think about that. Either way, it needs to be moved to its own issue, and this needs to be merged in. Assuming it works as intended, I haven't tested it myself.

Because cd can't change directories across drives on Windows for some reason, you'll need to add `C:` to the script somewhere. See the discussion on #241.

**Comment by IBNobody** [comment]
>I still haven't decided what I think about that. 

Sure. Let me know when you make a decision. I'd like to get buyin from multiple people before I did this.

> Because cd can't change directories across drives on Windows for some reason, you'll need to add C: to the script somewhere. See the discussion on #241.

I get around that by using `cd %MINGWPATH%` with `SET MINGWPATH="C:\MinGW\bin"` So the effective command is `cd C:\MinGW\bin`. Did I miss a non-relative CD elsewhere?

I'm not sure what we could do if MinGW is installed on a drive other than C, though.

**Comment by NoahAndrews** [comment]
Belieive it or not, running `cd C:\MinGW\bin` from a drive other than C: won't actually work, at least not on my Windows 8.1 system. Here's a screenshot.

image

I made sure the build guide tells the user not to change the default MinGW location, so I'm not too worried about supporting MinGW installs on different drives.

**Comment by IBNobody** [comment]
Ahh. I forgot about that. A simple fix is to issue a `CD /D` rather than `CD`. That way, you don't have to know what drive you're switching to. You only have to specify the full path. (`C:\MinGW\bin`)

**Comment by NoahAndrews** [comment]
Oh, nice. 

---- On Mon, 11 Apr 2016 14:15:33 -0400 IBNobody &lt;notifications@github.com&gt; wrote ---- 

Ahh. I forgot about that. A simple fix is to issue a CD /D rather than CD. That way, you don't have to know what drive you're switching to. You only have to specify the full path. (C:\MinGW\bin)

**Comment by IBNobody** [comment]
Fixed. Please buddy review the addition. :)

**Comment by NoahAndrews** [comment]
Looks great to me. Please do the same for #247. Read the commit descriptions for explanations of changes.

**Comment by jackhumbert** [comment]
Merging this :)

**Pull request merged**
