### PR TITLE
Update TMK_README.md

### PR DESCRIPTION
**Pull request by iFreilicht**
updated link to non-existent build.md file

### CODE REVIEW

**Comment by jackhumbert** [comment]
The one linked doesn't exist either :) I think it should be `/doc/build_old.md`

**Comment by iFreilicht** [comment]
Maybe I'm too dumb to link files then, I was trying to link this one: https://github.com/jackhumbert/qmk_firmware/blob/master/doc/BUILD_GUIDE.md

But it says it was already integrated into the main readme. I don't think linking to the old one is a good idea, as it's the same as build.md from the TMK repo, which doesn't include the QMK setup scripts. And those really make the whole process easier.

**Comment by jackhumbert** [comment]
The TMK readme really shouldn't exist at this point - it's too confusing for users. If you'd like to just have it link to the main readme (/readme.md) for now, we can merge this, and fix the real issue down the road (this is a big documentation change we're planning).

**Comment by iFreilicht** [comment]
Yes I think that would be a good idea. I changed it to link to the "Build Environment Setup" section directly. Not deleting any files for now.

**Comment by jackhumbert** [comment]
Perfect! Thanks :)

**Pull request merged**
