### PR TITLE
add sethbc keymap for gh60 and update macro expansion

### PR DESCRIPTION
**Pull request by sethbc**
I added my satan keymap for the gh60, but macro expansion in the hhkb keymap macro wasn't working quite right, so I cleaned up the macro expansion on KEYMAP_{ANSI|HHKB}.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Would you mind making the `KC_` prefix it's own definition - we've really adopted the `KC_*` as a standard in the keymaps (as opposed to TMK).

**Comment by sethbc** [comment]
Not sure I'm exactly following - do you want me to just go and clean-up the keymap to match the convention for the other keyboards?  I'm happy to do that when I've got a little time, was only following this convention as it's how the GH60 was set up when support was added.

**Comment by jackhumbert** [comment]
The `KEYMAP` definitions shouldn't prefix `KC_` (this is wildly inconsistent through the other keyboards right now, and is something I need to fix) - if you could add an additional definition like `KC_KEYMAP` that does the prefixing, that would be awesome.

**Comment by sethbc** [comment]
this is an interim fix, i can probably go through the keymaps in this directory and fix KC expansion and remove the other macros.  this is a pretty small directory.

**Comment by sethbc** [comment]
alright, this should do it - I killed KC expansion from GH60

**Comment by jackhumbert** [comment]
Awesome - thanks!

**Pull request merged**
