### PR TITLE
Fix aliases

### PR DESCRIPTION
**Pull request by eltang**
- Expand aliases into action codes at compile time
- Move the handling of certain keycodes to `quantum.c`

### CODE REVIEW

**Comment by jackhumbert** [comment]
There's some cool stuff here, but I don't really care for the liberties you're taking with modifying the core stuff. I agree that it needs work, but that's really something I'd like to do myself. 

It's also failed [most of the checks](https://travis-ci.org/jackhumbert/qmk_firmware/builds/136950333).

**Comment by eltang** [comment]
I can see, only three keyboards built and mine was one of them.

**Comment by jackhumbert** [comment]
Like we've mentioned before, smaller PRs are more likely to be accepted - @ezuk and I aren't comfortable merging in large or in-depth modifications done by you (even if it passed all the checks).

**Comment by eltang** [comment]
How would I have made this smaller?

**Comment by eltang** [comment]
I've been trying to make some other changes and I'm encountering difficulty because this PR wasn't merged. It'd be great if you could revisit it soon.

**Pull request closed without merging**
