### PR TITLE
Adds keymap based on Kinesis advantage

### PR DESCRIPTION
**Pull request by finleye**
This is a keymap similar to the Kinesis Advantage for the Atomic and the Preonic

### CODE REVIEW

**Comment by sethbc** [comment]
you've got some errors in your atomic keymap, check the travis buildlog

**Comment by jackhumbert** [comment]
Looks like you're missing a comma on /keyboards/atomic/keymaps/kinesis/keymap.c:53:32!

**Comment by finleye** [comment]
Thanks! I'll take a look. I made the Atomic layout and realized I wanted a
Preonic, so I've been more focused on that. I might just drop the Atomic
layout from this PR

**Comment by finleye** [comment]
@jackhumbert I'm also working on writing firmware for my Infinity 60% from Massdrop. Should do you know if I should checkout the infinity_chibios or should I just port the infinity keyboard from the tmk project?

**Comment by jackhumbert** [comment]
I believe you should use the infinity_chibios - @fredizzimo may be able to answer that fully though. I'm not super familiar with which boards are which.

**Pull request merged**
