### PR TITLE
Added XD60 Support

### PR DESCRIPTION
**Pull request by stanleylai**
Added support for the new XD60 PCB.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Nice! I'll merge this now, but I do wonder if it would make sense to group this into the GH60 as a subproject, or if some other project name (besides GH60) makes sense for boards that are derived from/are the GH60.

**Comment by stanleylai** [comment]
I wondered the same. Would be happy to make this a sub of GH60 if you prefer!

**Comment by jackhumbert** [comment]
Do you know if this is only available via taobao? I guess I'd rather have boards that are widely available/made by small businesses in the main directory, and others as subprojects.

**Comment by backstabbd88** [comment]
@stanleylai good day,
i just want to thank you for sharing the xd60 code. I just built my first custom mechanical keybaord with this, for someone like me who have no programming background, this save me lot of time of research,

Thank you so much

**Comment by stanleylai** [comment]
@backstabbd88 awesome! glad to hear
@jackhumbert sorry, missed this thread! yes, its only available on taobao. Just realized as I was working on it, there are some differences in terms of how the GPIO pins are used. But the matrix is the same AFAIK. Be happy to make this a subproject of the gh60 if you prefer!

**Comment by jackhumbert** [comment]
This is ok for now - we might convert it over later :)

**Comment by Dbroqua** [comment]
Hello,

Where we can find this PCB ?

Regards,
DarKou

**Comment by stanleylai** [comment]
@Dbroqua https://world.taobao.com/item/537485105086.htm#detail

**Comment by Dbroqua** [comment]
Hello @stanleylai ,

Thank you ! 

But I'm not sure if I can buy one of them (I'm living in France and I don't really know taobao).

**Comment by backstabbd88** [comment]
@Dbroqua i can recommend https://www.taobaoring.com/ as agent if you intend to buy from taobao. they're cheaper than bhiner and they're very responsive.

**Comment by Dbroqua** [comment]
Thank you @backstabbd88

**Pull request merged**
