### PR TITLE
Unicode

### PR DESCRIPTION
**Pull request by mecanogrh**
to have unicode input you need to:

- set your OS input method to UNICODE if needed
- enable unicode in your makefile
- copy the action_function from
keyboard/planck/keymaps/unicode/keymap.c to your keymap.c
- set the target OS method in your keymap.c: 
```c 
void matrix_init_user() {
    set_unicode_mode(UC_OSX); 
} 
```

you can then switch when you want with:
```c
set_unicode_mode(UC_OSX); 
set_unicode_mode(UC_LNX);
set_unicode_mode(UC_WIN);
```
- put some unicode codes in your keymap like so: 
```c
UC(0x0061)
```

I did change the bit mask in quantum/keymap_common.c and .h
I’m afraid we will need uint32 to get a total support for all unicode
tables or relocate the handler as @mbarkhau did.

### CODE REVIEW

**Comment by mecanogrh** [comment]
> jackhumbert commented 9 hours ago
Haha, it's not bad, just not designed to do fancy stuff like deleting 162 commits :)

I think we can drop the "keymap" terminology, and this file will likely get absorbed by the quantum.c file that's coming in the following weeks (in the leader-key branch).

Ok cleaned and moved keymap_unicode.c to keyboard/planck/keymaps/unicode/ in the meantime.
Going to check your link to implement the 32bits mask so we can have full and clean support for Unicode.
One thing bother me though, with audio and midi using action_function as well how the code in this function is supposed to make the difference when the action is coming from different handlers?

**Comment by mecanogrh** [comment]
There is a typo in the unicode.c file a surnumerous
```c
		unregister_code(KC_LALT);
```
which doesn't prevent the code from working, I'll fix it in a next pull request once this one has been accepted.

**Comment by jackhumbert** [comment]
If you fix it in your branch, it should update the PR automatically :)

I think this still has the limitation of only working through 0x0FFF - the 8bit variables we're pulling from to generate the unicode aren't truly 8bit. Were you able to generate characters above that?

**Comment by mecanogrh** [comment]
I just fixed it in my branch with a new commit :)
Just tried to go beyond Tibetan (ending at 0x0FD8) and yes no luck, I would have though we maybe could go up to sinograms (0x6FFF) with a 0x9000 mask. Another good reason to look at the 32bits code.
What's up with all these ACTION_FUNCTION (_OPT or not) going to action_function()?
Isn't there a flaw by design here?
If I have both midi and unicode enabled how to differenciate one from another in action_function so the midi is not interpreted as unicode?

**Comment by jackhumbert** [comment]
I'm not seeing it on yours: https://github.com/mecanogrh/qmk_firmware/commits/unicode :/

Check out the quantum file on this branch: https://github.com/jackhumbert/qmk_firmware/blob/midi-update/quantum/quantum.c - this will be how the Unicode is implemented in the future, allowing for up to 0x7FFF (with the 0x8000 mask).

**Comment by jackhumbert** [comment]
The changes on the (now defunct) branch have been merged, so we can work things into that file now :)

**Comment by jackhumbert** [comment]
I'm moving this to #333 - let me know what you think over there!

**Pull request closed without merging**
