### PR TITLE
Clean up default keymaps

### PR DESCRIPTION
**Pull request by eltang**
Someone really needs to set their tab length to 4.

@jackhumbert What do you think about swapping Backspace and Delete in the default Preonic keymap? That might make it a little easier for Planck users to transition.

### CODE REVIEW

**Comment by eltang** [comment]
Don't merge. Needs fix.

**Comment by jackhumbert** [comment]
Sorry, I'm sticking with calling that layer "adjust."

The unicode box stuff is cool, but is kind of unnecessary. It just forces people to have to copy/paste characters when making changes (for personal keymaps, etc).

I like the enum for the layers - I'll have to think about that more though.

Tab length is really a non-issue here. 

The Preonic and Planck keymaps are going under heavy development right now - they don't really need to be touched until things have been finalised.

I thought about the backspace/delete swap, but most people switching to the Preonic are used to their backspace on the number row - as someone that switches between them, that bugs me too :)

If you wanna pull out the `~`/`!` swap for the layer off shortcut, I can get that merged.

**Comment by eltang** [comment]
That last item—it's supposed to be that way. `!layer_state` will be zero if any of the layers are on, and that's not what's supposed to happen.

I'll restore the "Adjust" name.

**Comment by jackhumbert** [comment]
Yeah, I meant so I can merge just that - I'd like to wait on the rest of it.

**Comment by eltang** [comment]
Oh.

**Comment by eltang** [comment]
Oh.

**Comment by eltang** [comment]
What do you think about putting Oneshot modifiers in the default layout to make certain shortcuts easier to execute? Would those be too confusing to users who haven't used them before?

**Comment by jackhumbert** [comment]
I think that would probably be too complicated :/ I'm kind of pushing it as it is with the tri-layer stuff.

**Pull request closed without merging**
