### PR TITLE
Added WS2812 support for KC60

### PR DESCRIPTION
**Pull request by stanleylai**
Added sample images, plus requisite setup code.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Cool! Would you mind moving this to a different keymap? The default should be as the kc60 comes w/o modification. You can move the relevant Makefile options to the keymap's Makefile as well.

The rgblight_init is also [here](https://github.com/jackhumbert/qmk_firmware/blob/6955719075a9a07524814e4183f3f90f83db1c6a/tmk_core/common/keyboard.c#L96), so it's not needed to call it from the kc60.c file.

**Comment by stanleylai** [comment]
That's a great idea. Also, had no idea I could place the Makefile within the keymaps! Never done it before, so let me know if its not quite right.

**Comment by jackhumbert** [comment]
Nice! Can you revert the default keymap and the kc60/Makefile to what they were originally?

**Comment by stanleylai** [comment]
Ah yes, my bad. Done.

**Comment by jackhumbert** [comment]
Awesome! Thanks!

**Pull request merged**
