### PR TITLE
Added Ergodox Layout with persistent layers, Atreus corrections

### PR DESCRIPTION
**Pull request by Xyverz**
I've added my Ergodox layout, complete with persistent layers. I can rearrange the order to make Qwerty the default if needed.

I've corrected the spelling of Atreus in the Makefile for the Atreus keyboard.

I've also updated my keymap for the Atreus.

My Phantom layout wasn't ready for primetime, so I removed it from my repo. (It shouldn't be in the master yet anyway...)

### CODE REVIEW

**Comment by Xyverz** [comment]
I have a conflict message here. How do I resolve that?

**Comment by Xyverz** [comment]
Added the MiniVan to the keyboards list.

**Comment by jackhumbert** [comment]
Cool! For the conflicts, make sure you `git pull` the latest changes from here - you may need to make a merge commit, but it should fix things!

**Comment by Xyverz** [comment]
by pull the latest changes from here, you mean from the main qmk branch?

**Comment by jackhumbert** [comment]
Yeap!

**Comment by Xyverz** [comment]
OK, looks like I've fixed the conflicts now. I guess it helps to have the official repo as the upstream. *sigh* Yeah, I'm still new to Git.

**Comment by Xyverz** [comment]
Hey Jack, it looks like my ErgoDox layout doesn't work with the Infinity due to the way the array is setup. It compiles just fine with normal and EZ though. Can I do something with config.h or makefile that would have the infinity skip it all together? Otherwise, should I put a comment in the keymap saying "this doesn't work with the Infinity" or would you rather I just remove it from the repo?

**Comment by jackhumbert** [comment]
It should be fine - you're only getting warnings :) thanks for doing all this!

**Pull request merged**
