### PR TITLE
Move vibrato table to program memory

### PR DESCRIPTION
**Pull request by eltang**
I noticed that `avr/pgmspace.h` was included in `vibrato_lut.h` but not used.

### CODE REVIEW

**Comment by jackhumbert** [comment]
@IBNobody and I had talked about this, and we believed it was faster to leave it out of program memory - execution speed is really a factor since this is inside the ISR :)

**Comment by eltang** [comment]
Oops. You might want to remove the header file then. Don't merge my other PR yet. Somehow most of my changes got left out.

**Comment by jackhumbert** [comment]
Are you using Github's app on your Mac? That might make it easier to manage commits and stuff.

**Comment by eltang** [comment]
I have it, but I'm not actively using it. The other PR's ready now, though!

**Pull request closed without merging**
