### PR TITLE
Kastyle refresh

### PR DESCRIPTION
**Pull request by chwilk**
This is a refresh of the kastyle keymap, a Kinesis Advantage based map that includes some features of the kines-ish layout with a one-handed feature (activated by the bottom left and bottom right keys) which mirrors the keyboard for one handed use.

### CODE REVIEW

**Comment by chwilk** [comment]
It seems that turning on the handedness feature requires all keymaps to define a hand_swap_config array. I'll try moving this into the ergodox/ez setup.

**Comment by ezuk** [comment]
Thanks @chwilk! Any chance you could add a readme.md describing the layout and the reasoning behind the handedness?

**Comment by chwilk** [comment]
No problem!

**Comment by ezuk** [comment]
Wonderful! Thank you, merging! :)

**Pull request merged**
