### PR TITLE
Makefile overhaul

### PR DESCRIPTION
**Pull request by fredizzimo**
Here comes a scary pull request(it turned out to be much bigger than I had anticipated)... I recommend that we let it rest a little bit for proper review and/or testing by several people before merging. 

I have been testing it quite much myself, but the magnitude of the changes are huge, and I hope I have been taken care of everything. 

The readme.md file best explains the new syntax for running make. 

The biggest reason for the huge number of files changed is that keyboard and subproject makefiles have been split into Makefile and rules.mk. The documentation also had to be updated in many files. Other than that the changes are quite localized.

The individual commit descriptions best describe what have been made. But here's a quick overview of what has been done from issue #591, (1. and 2.  and 9. were fixed before). 3, 4, 5, 7 (partly), 8 (but keymaps still use only a single Makefile).

Additionally there are a couple of optimizations. 

#582, or keep going even after a keyboard compilation fails is now on by default (it doesn't check the -c option). I figured it was better to do without, as you can always press Ctrl-c if you want to abort the compilation in the middle.

There's also an unrelated change, since my previous make file changes, diff-utils have been needed for the cmp command. So that have now been added to Travis and install-dependencies.sh. The instructions have not been updated since they seemed to be incomplete even before, and needs a separate update pass.

The root Makefile, could perhaps benefit from a bit more comments, an I will probably add that tomorrow.

### CODE REVIEW

**Comment by fredizzimo** [comment]
Seems like I forgot the new amj60 keyboard.

**Comment by fredizzimo** [comment]
Ok, I fixed it and rebased it to the correct commit

**Comment by fredizzimo** [comment]
This pull request is not just scary, it's the devil himself or number 666.

But on the positive side, it reduced the Travis compile times by over half, 14 minutes now compared to 30 minutes before.

One thing that I forgot to tell in the original message, is that most of the old variable syntax is still supported, so you can still run `make keymap=fredizzimo` for example.

**Comment by fredizzimo** [comment]
I have now quite extensively commented the main Makefile, hopefully it will make it a bit easier to read and maintain.

I also fixed a minor problem with the clean targets, they didn't clean everything as they should.

**Comment by algernon** [comment]
There's one issue I have discovered with this so far: if I have a keymap that has a dash in its name, then the former `make keyboard=ergodox keymap=algernon-master` way of building it (from the root directory) does not work anymore.

For the sake of backwards compatibility, would it be possible to not parse the target/programmer/whatever out of the keymap name?

The interesting thing is that the above command works if I use `zweihander-osx` for example, but not my keymap (which was checked out into `keyboard/ergodox/keymaps/algernon-master`, so its not part of the upstream repo).

**Comment by fredizzimo** [comment]
Thanks for the bug report @algernon.

I haven't tested this myself yet, only read the code and done some speculation. But I probably will later today.

However if I'm right the full command wouldn't work either
`make ergodox-ez-algernon-master`, which is the same as what the DEFAULT_GOAL internally turns your command into. On the other hand the old syntax would work in certain situations like this `make all keyboard=ergodox keymap=algernon-master` Notice the **all**.  

It's quite easy to see what the problem with `make ergdox-ez-algernon-master` is though. The problem is that the rule parsing don't do the longest match for the keyboard and subproject names. So the above would try to compile `algernon` with `master` as target.

Implementing a longest match in the makefile syntax, would be pretty hard, at least I can't think of an easy way right now. But I will leave this for a while and see if I can think something up.

Otherwise, I guess we have to change the separator, maybe this kind of syntax would be better `make ergodox.ez.algernon-master.dfu`?

**Comment by fredizzimo** [comment]
I will most likely implement the longest match. I think I have found an easy way.

Just remove the current match from the list and recursively try until no match is found.

**Comment by algernon** [comment]
I don't really see the benefit of having the target in there, it seems to complicate things more than what it makes easier. There are many, many reasons why I'd want to compile, but not flash. But I may be misunderstanding something, I only had a quick look so far.

As for the other syntax: eww. I'd prefer if what works today, would continue working, so the target parsing stuff would be removed, at least when using the old make calling convention.

**Comment by fredizzimo** [comment]
Yes, you are able to compile without flashing, with both target syntax and the old variable syntax. 

I only added the `dfu` in there to show an example that doesn't trigger the bug.

I will soon have the longest match parsing done and then the problem will disappear.

BTW, the new syntax that I offered `make ergdox.ez.algernon-master.dfu`, was an alternative to `make ergodox-ez-algernon-master-dfu`, and not to the long variable based syntax `make keyboard=ergodox subproject=ez keymap=algernon-master`.  This would have removed the ambiguity of using `-` both as a separator and valid keymap name, which is ultimately what triggers the bug.

If people prefer, we could remove the shorter `make ergodox-ez-algernon-[target]` syntax completely, and always require the full `make [target] keyboard=ergodox subproject=ez keymap=algernon-master` syntax. That would certainly simplify the implementation a bit, but maybe not as much as you would think, since we would still need to handle missing variables and special ones like `allkm` or `defaultsp` . If variables were to be used then those could be shortened to `all` and `default`, since there's no longer any ambiguity.

But in that case we should remove the shortcuts that we have now, like `make all-keyboards` and `make all-keyboards-defaults`, instead you should write `make keyboard=all` and `make keyboard=all keymap=default`. We would also lose the ability to run `make ergodox-ez-algernon ergodox-ez-fredizzimo`, which would compile both keymaps in the same command and is possible with this pull request. And also the simple case, when running this from the keyboard directory `make algernon`, will build the algernon ez keymap with this pull request. With a variable only syntax you would always have to write `make keymap=algernon`

The reason why I would remove them, is that they are not consistent, and would require quite a bit of extra support to maintain. And we would need to duplicate them for things like make all-keyboards-clean, unless we find a way to work around some implementation problems that we had with the old system. 

But well, in any case, once the bug is fixed there shouldn't be any problems in your use case.

**Comment by fredizzimo** [comment]
The bug should be fixed now, but I also found another unrelated bug. The infinity dfu-util commands don't work. I'm sure it's was working very recently, so I must have introduced a regression at some point.

I will fix that now

**Comment by fredizzimo** [comment]
Ok, that was a variable assignment order problem, and should be fixed now.

**Comment by fredizzimo** [comment]
I fixed a small inconsistency issue.

When running `make` from either a keyboard folder or a subproject it builds all keymaps for all subprojects and the selected subproject respectively. Without this fix, the same doesn't happen if you run `make clean` for example. As it would just provide you with an error message. Now this will work as expected.

**Comment by fredizzimo** [comment]
Closing and re-opening to trigger Travis.

**Comment by fredizzimo** [comment]
This pull request is getting a bit hard to keep up to date and I will soon have the unit testing pull request, which builds on this, ready. So it would be good if it could be merged soon.

There are some line ending inconsistencies (most likely caused by the .gitattributes changes that prevents me from rebasing properly, so the last two updates had to be done through merges. But unfortunately it also means that any change made to a keyboard or subproject makefile won't propagate to the rules.mk file anymore. And I have to resolve that manually, so it's very error prone.

Personally I haven't found any problems with this.
@algernon, Did you have a chance to test my fix already, and could you please confirm that it works?
@jackhumbert Have you been able to test this at all. Do you have any comments or improvements that should be done before merging?

One quick way to test different make commands is to use the show_path target, which doesn't compile,  but still shows what would be done, so it's much faster that way.

**Comment by jackhumbert** [comment]
Agreed! I'd like to merge this soon - I'll try to set aside some time today to dive into it. It's been a while since I've been able to pull/compile locally :)

**Comment by sethbc** [comment]
FWIW, this runs okay for me.  i'd probably add an alias to clean all ("make clean"?)

**Comment by fredizzimo** [comment]
Yes, adding a make clean from the root would be a good idea.

I think I'll implement it so that it just deletes the whole .build folder, instead of calling each target sepearately, which `make allkb-allsp-allkb-clean` would do.  That should speed up the cleaning considerably.

**Comment by jackhumbert** [comment]
Messing around with this a bit, and I'm comfortable merging it! The only thing I might suggest is a `make help` for those too lazy to look at the documentation :)

My current understanding of the order of merging is #666, #691, and then #690 once you're comfortable with it - is that accurate?

**Comment by fredizzimo** [comment]
Yes, the order is correct. #691 will probably break after the merge of #666, but I will fix it if it does. #690 (Unit testing) will be rebased on top of the other merges.

**Comment by fredizzimo** [comment]
Hm When working on the unit test compilation, I just noticed that compiled_push doesn't work. 

```
1.14s$ bash util/travis_compiled_push.sh
Making ergodox/ez with keymap steno and target all-keymaps
build_keyboard.mk:44: *** "keyboards/ergodox/ez/ergodox/ez.c" does not exist.  Stop.
util/travis_compiled_push.sh: line 14: GH_TOKEN: unbound variable
```

So this probably have to be fixed before merging. 

@jackhumbert Why is it trying to compile the Ergodox keyboards again there?

**Comment by jackhumbert** [comment]
There's a line (`make all-keymaps keyboard=ergodox/ez AUTOGEN=true`) in the script that recompiles the EZ files, so those get used on qmk.fm instead of the infinity ones. It's a temporary fix until I'm able to implement subprojects into the qmk.fm generation.

`make all-keymaps keyboard=ergodox/ez AUTOGEN=true` should be able to be replaced with `make keyboard=ergodox AUTOGEN=true`, right?

**Comment by fredizzimo** [comment]
Yes, that should work, but I changed it to the more simple form
`make ergodox-ez AUTOGEN=true`,

`make ergodox` would compile both EZ and Infinity.

**Comment by fredizzimo** [comment]
Everything seems to be OK now, I assume that the `util/travis_compiled_push.sh: line 14: GH_TOKEN: unbound variable`, is caused by not starting the compilation from the master branch. And that's what currently prevents pull requests from updating the qmk.fm.

**Comment by jackhumbert** [comment]
Awesome! Yeah, I really got lucky there with avoiding that issue :) Merging now!

**Pull request merged**
