### PR TITLE
Fix RESET key not working on Ergodox EZ keyboard.

### PR DESCRIPTION
**Pull request by Rovanion**
A declaration of controller chip was missing in the config.h.

### CODE REVIEW

**Comment by jackhumbert** [comment]
I'm not sure this is needed - no other projects that I can find define this anywhere. It may be added in at compilation.

**Comment by aspickard** [comment]
+1 Fixes the issue for me

**Comment by jackhumbert** [comment]
This is interesting - your bootloader.c is [unmodified](https://github.com/jackhumbert/qmk_firmware/blob/master/tmk_core/common/avr/bootloader.c), and you're calling `bootloader_jump()`, right?

**Comment by jackhumbert** [comment]
To bring over other comments, it looks like the referenced `__AVR_ATmega32U4__ ` is commented out with `#if 0` [here](https://github.com/jackhumbert/qmk_firmware/blob/master/tmk_core/common/avr/bootloader.c#L117) - is anyone else seeing things differently?

**Comment by aspickard** [comment]
I just updated my repo to the newest master and did a clean make (without these changes) and everything worked fine for me.  May have been fixed in another commit.  :beer:

**Comment by jackhumbert** [comment]
Ahh - @alcesleo, could you weigh in here?

**Comment by DidierLoiseau** [comment]
For the record, the `if 0` was introduced in 4d64fd8faa8; the file was later moved, in commit 05caacc.

**Comment by jackhumbert** [comment]
@aspickard do you know what commit you were on when making these changes? Maybe we can track down the commit that fixed/changed things.

**Comment by aspickard** [comment]
9814343 I was a bit behind :X

**Comment by Rovanion** [comment]
Perhaps I should try using the reset key against an unmodified master when I get home again to see if the RESET button actually works on master nowadays? It could be that I was on an old revision too when I picked up on the issue.

**Comment by DidierLoiseau** [comment]
I just tested it too and it works for me… kind of.

In fact, the reset key does not work immediately after reloading the firmware with the teensy button. It only works after I unplug and re-plug the keyboard. After that, it works all the time… until I use the teensy button again.

I think the first time I tried to add a reset key (back when @alcesleo created #112), I didn't try to unplug the keyboard.

I'm currently on d33681a without modifications outside my own keymap.

**Comment by Rovanion** [comment]
The results are in and I'm terribly sorry to have wasted everybody's time: Turns out that the RESET button works with the current origin/master _as well_ as with my local master which I must have updated at some point between noticing the issue and checking into the thread at #112. 

It's too bad that the RESET button did work on my local master, because if it hadn't we could have gotten a span of commits during which the feature was fixed. Oh well.

**Comment by aspickard** [comment]
I can confirm the same behavior that @DidierLoiseau reports - if I use the Teensy button, then I can't use the software reset unless I unplug and replug the keyboard.

**Comment by Rovanion** [comment]
Can confirm the same behavior here too, same as what @DidierLoiseau and @aspickard are describing.

**Comment by Rovanion** [comment]
Well this PR should be closed and replaced with an issue on the topic since the code attached doesn't fix the issue at hand.

I went ahead and opened Issue #164 for this purpose.

**Comment by ezuk** [comment]
Thank you, Rovanion!

**Pull request closed without merging**
