### PR TITLE
Add serial link library

### PR DESCRIPTION
**Pull request by fredizzimo**
I'm opening a pull request at this stage to ask a few questions about this, so don't merge yet.

This adds the serial_link library that I have written to support the communication between the two halves of the Ergodox Infinity. 

* It takes care of packetising messages over a serial link (in the case of Ergodox the UART), but it could also be used for other types of channels. 
* It also make sure that corrupted data is ignored and not transferred to the application. 
* There's also a quite easy interface for defining which kinds of objects are transferred over the channel, that's using a fixed amount of memory. 
* It supports a chain of serial links, where each link is daisy chained to each other, at least for unit tests. 
* It's quite well unit tested.
* It's tested with ChibiOS, but quite easily be made to work with AVR too

Initially this will only be used for the Infinity Ergodox, but another potential use case would be for any keyboard -> computer communication over USB. This could be used for making an host application on the PC, which would run all of the QMK code, while the keyboard would mostly just send the scancodes to it. This way we could try out keymaps, and debug the firmware on the PC. But of course that host application has to be made first.

My questions are the following.

1. Is it a good idea to include this in QMK, or should it be as a project of the keyboard at this stage?
2. Would the location quantum/serial_link be a good location?
3. All the commits are brought in exactly as I originally committed them, and there's around 60 of them. The commits are well contained and small with quite good descriptive messages. But do you want me to try to combine some of them to get the commit count down?
4. I could add it as a sub-module instead of a sub-tree, but it's a pain to develop that way, and if it's included in QMK, I could get rid of the original repository completely, so I rather keep it as a sub-tree, is it OK?
5. [The Unit Test Question](https://github.com/jackhumbert/qmk_firmware/issues/479)
6. The license is MIT, but the QMK as a whole is GPLV2 (I don't see any license for the QMK in itself, but at least TMK is GPL, or at least parts of it, so QMK has to be too). License wise I think it's OK to leave this folder as MIT(although the effective license is GPL), is that OK, or should I remove the license file and headers?

Depending on the answers to the questions, this could potentially be merged already, but there's absolutely no hurry to do so yet.

### CODE REVIEW

**Comment by jackhumbert** [comment]
1. Yeah! I like this a lot, especially the host application idea. Allowing the keyboard to optionally talk to a host application with a fall-back keymap sounds really cool.
2. Would this make sense in the lib? I've been wanting to restructure the tmk_core and quantum folders as well.
3. Nah, that should be fine. I just want to try to avoid the stupid commits I make all the time.
4. Sub-tree sounds fine!
5. I'll comment on that there.
6. I'm pretty unfamiliar with licenses, so I'm happy to defer judgement to you! We could potentially open another issue about this.

**Comment by fredizzimo** [comment]
Ok, I can move it to the lib folder tomorrow (I should go to bed now). 

The reason I didn't move it to the lib folder initially was that I wanted to keep the completely external libraries, like ChibiOS, separated from the ones that we have control over. And I would still like to see that separation. So maybe some other structure would make more sense? Or do you think it's better that everything is in the lib folder.

There's also some other library-like things in the quantum folder, like the audio, so maybe something common for that? 

We should probably continue this discussion in your newly opened issue https://github.com/jackhumbert/qmk_firmware/issues/483. I'll check if you already have some other suggestion there before I move it to the lib folder. But you don't need to hurry with the decision, I can continue my work, and fix up things later, when it's decided.

**Comment by algernon** [comment]
To chime in on the license question: MIT is GPL compatible, meaning that the combined work will be GPL, but if someone wants to reuse just the MIT parts, they can do that under the MIT license. So this combination is legally fine, and is practical too, unless there's a strong reason to have everything under one license (but it seems to me there's no such effort).

(IANAL, but I have to do license compliance checks almost daily at work, so there's a bit of experience there :)

**Comment by fredizzimo** [comment]
I think this can be merged now, if you prefer. Note that, this commit just adds the library itself, so it should be very unlikely that this breaks something, now that the Cgreen submodule is removed. 

I'm building my other pull request to add actual support for the keyboard and adding unit tests based on this.

The location is still in the qmk folder, but we can do a simple move, and make some small makefile changes later on when we decide the final location

**Comment by jackhumbert** [comment]
Awesome!

**Pull request merged**
