### PR TITLE
Add Minorca keyboard

### PR DESCRIPTION
**Pull request by messiach**
Added the Minorca to this firmware if you're interested.

### CODE REVIEW

**Comment by iFreilicht** [comment]
Nice, saw your post on /r/mk a while back. Looks all fine to me, apart from the missing documentation.

Why is F11 on Fn0 alone while all other function keys are on Fn1? Is that intentional?

Also, a small hint: Instead of using the curly bracket initialiser lists for each keymap, use the `KEYMAP` macro that you defined in `minorca.h`, that way you don't have to insert XXXXXXX into every position that's mapped on the keymap.

**Comment by messiach** [comment]
Hi - the F11 was a remnant of a previous layout - I was shuffling a few
things around and must have forgotten to switch it over to the Fn0 layer.

I had originally attempted to use the KEYMAP macro (which is why my keymap
macro is even there), however I ran into issues when attempting to add keys
for which there wasn't a shortcut already created, like this:

S(KC_QUOT)

I don't believe the KEYMAP macro supports this, so I took the lead from the
Planck setup where the KEYMAP is also there but not used.

Let me know if you'd like me to fix the F11 key or anything else.

**Comment by iFreilicht** [comment]
Ah I see. I had the same issue, so I just removed all occurences of  `KC_##` in the macro and added a `LEGACY_KEYMAP` macro that had the `KC_##` still in it.

I think it would be good if you could fix the F11, just to give people a better starting point when they want to create their own layouts and to avoid confusion about its position.

**Comment by messiach** [comment]
I went ahead and fixed F11 and pushed the changes - running through travis
now.

**Comment by iFreilicht** [comment]
You forgot to put `KC_` in front of `F12` in `keymap.c`.

**Comment by messiach** [comment]
Whoops - trying to do too many things at once today.
Fixed.

**Comment by jackhumbert** [comment]
Does this have a PCB? We just merged in a handwired version here: https://github.com/jackhumbert/qmk_firmware/tree/master/keyboards/handwired/minorca (we're trying to keep PCBs at the top level, and handwired boards in `/handwired`).

**Comment by messiach** [comment]
Ah I see - ignore my request then, this is hand wired. Sorry about that - didn't think to look in that folder (thought it was just general hand wired).

via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=8.6.48&pv=9.3.4&source=email_footer_2]
On Wed, Aug 17, 2016 at 9:14 PM, Jack Humbert <notifications@github.com> wrote:
Does this have a PCB? We just merged in a handwired version here: https://github.com/jackhumbert/qmk_firmware/tree/master/keyboards/handwired/minorca [https://github.com/jackhumbert/qmk_firmware/tree/master/keyboards/handwired/minorca] (we're trying to keep PCBs at the top level, and handwired boards in /handwired ).

**Comment by jackhumbert** [comment]
No worries! Feel free to add your keymap to that one :)

**Pull request closed without merging**
