### PR TITLE
Clean up #343's code

### PR DESCRIPTION
**Pull request by eltang**
I failed to see that the scopes of these variables could be limited.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Can you describe your changes more?

**Comment by eltang** [comment]
I just limited the scope of variables.

**Comment by jackhumbert** [comment]
And why that helps? I'm asking so that you put these things in the initial description :)

**Comment by eltang** [comment]
It's just good programming practice to do that as much as possible.

**Comment by jackhumbert** [comment]
Explaining why it is a good programming practice is more helpful than stating that it is one.. sometimes I think this is futile.

**Comment by eltang** [comment]
Oh. It reduces the risk of creating variables with conflicting names and it also helps the compiler optimize code by showing it the exact place that the variable has to be used.

**Comment by jackhumbert** [comment]
Thanks - put these things in the description next time. It'll help me and others quickly and accurately assess your changes, and get things merged faster.

**Comment by eltang** [comment]
Sorry, I kinda assumed that it was common knowledge.

**Comment by jackhumbert** [comment]
That's kind of missing the point - you need to describe your changes more. In situations like this, a manager of some sort (even a engineering manager) will be reviewing your changes to see if they make sense, and it's safe to assume they won't have time to read through each line and see what your intentions are, or even know what the code does (I certainly haven't read/touched every TMK core file). Your descriptions should be pitches on why the code should be merged, what the changes do, how that's helpful to others/the codebase, etc. 

> I failed to see that the scopes of these variables could be limited.

Personal info like this isn't really relevant to the changes you're making.

**Comment by eltang** [comment]
Gotcha.

**Comment by eltang** [comment]
Is there a good rule of thumb for how often to open PRs? I thought #343 was fairly complete, but then I discovered the changes in this PR and now, I've discovered another that can shave 180 bytes off the final size of the .hex file. I just don't want to annoy you with too many PRs.

**Comment by jackhumbert** [comment]
I would be happy with one a week - you can take time to perfect things over the course of a week in your branch before making the PR. If you have questions about things, you can tag me on your fork, but please limit them.

**Comment by eltang** [comment]
Yes, sorry, I'm still very new to PRs.

**Comment by eltang** [comment]
@jackhumbert The changes I've made so far have done both, but you care more about optimizing for size than optimizing for speed, correct?

**Comment by jackhumbert** [comment]
It sounds like you might be trying to ask another question about implementing something - can you ask that instead? I don't think speed's ever really been an issue with the keyboard stuff, just audio (for me).

**Comment by eltang** [comment]
What makes you think that? I haven't really thought about implementing anything new yet—I'd rather finish cleaning up the existing code instead.

**Comment by jackhumbert** [comment]
Sorry, not sure. Sounds good.

**Comment by eltang** [comment]
I'm interested in what problems you've run into with the audio, though. Might I be of assistance (after decking out my PCB with a speaker)?

**Comment by jackhumbert** [comment]
It's mostly clocking limitations - it's part of the reason we're looking at bigger/better chips.

**Comment by eltang** [comment]
You mean the actual chip doesn't run fast enough?

**Pull request merged**
