### PR TITLE
Visual studio + vi/viemu ergodox layout

### PR DESCRIPTION
**Pull request by xsolon**

### CODE REVIEW

**Comment by ezuk** [comment]
Hey @xsolon, just wondering, why'd you close the PR?

**Comment by xsolon** [comment]
The signature of a couple of methods changed since i got latest so it wasn't compiling. I'll submit it again shortly.

Sent from my iPhone

On Apr 24, 2016, at 7:52 PM, Erez Zukerman <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @xsolon<https://github.com/xsolon>, just wondering, why'd you close the PR?

-

**Comment by ezuk** [comment]
@xsolon just wondering, which methods and what does `git blame` say? Who changed them, what commits? (currently looking into changes that are breaking keymaps, which is why I'm curious.)

**Comment by xsolon** [comment]
Didn’t bother to check who/when but here are the signature changes:

void * matrix_init_user(void){
void * matrix_scan_user(void) {

void matrix_init_user(void){
void matrix_scan_user(void) {

**Comment by ezuk** [comment]
@jackhumbert does that ring a bell?

**Comment by eltang** [comment]
That was @yoyoerx's doing in #190! [This script](https://github.com/jackhumbert/qmk_firmware/blob/master/keyboard/ergodox_ez/190hotfix.sh) should fix the keymap!

**Pull request closed without merging**
