### PR TITLE
Improve compilation

### PR DESCRIPTION
**Pull request by eltang**
- Copy a change made in TMK that somehow didn’t make it (remove extraneous dfu-programmer commands)
- Make code size estimates much more meaningful

### CODE REVIEW

**Comment by jackhumbert** [comment]
The move to testing .hex files was [a conscious one](http://stackoverflow.com/questions/13392092/why-is-the-uploaded-binary-size-so-much-smaller-than-the-actual-size), and `-C` isn't available on all versions of `avr-size`.

What dfu-programmer commands are you talking about?

**Comment by eltang** [comment]
`avr-size` strips down the .elf file to what's actually going to go on the chip. The number it outputs is exactly the same as the number in the old output, the only difference is that the size is now given as a percentage of the space available on the chip (much more useful). Should I change `-C` to `--format=avr`?

I'm talking about tmk@d0f1749.

**Comment by jackhumbert** [comment]
It does the same to the .hex file. The avr format is also not supported by all versions.

I'd like to keep the size information, but I see the redundant erase - feel free to modify your PR to just that.

**Comment by eltang** [comment]
Done.

**Comment by eltang** [comment]
I think some documentation on running `avr-size` manually would be nice (it took me a while to figure that one out).

**Comment by jackhumbert** [comment]
Putting `-h` after the command usually provides enough. eg `avr-size -h`.

**Comment by eltang** [comment]
That's not what I meant; learning how to use it is easy, but learning that it even exists (and is capable of outputting much cleaner output than it does when called by `make`) is not.

**Pull request merged**
