### PR TITLE
Makefile: Keep going when building with make -k

### PR DESCRIPTION
**Pull request by algernon**
Instead of failing early on the first error, when building with `make -k`, keep going until the end, and only fail the build then.

### CODE REVIEW

**Comment by algernon** [comment]
Still working on this one, there are some issues to iron out. The next push should make it behave properly...

**Comment by algernon** [comment]
This last one should do. Worked locally. There may be build failures nevertheless.. at least I've seen some when building on my laptop, but I doubt those are the results of this change.

**Comment by ezuk** [comment]
Yeah, CI bombs on this one for some reason, so not merging for now. You think the errors are not related to this branch?

**Comment by algernon** [comment]
Not sure. I see `[ERROR]` messages in my local build, but none here, will have to investigate further, to see where the problem may be. Will try to do that during the weekend.

**Comment by algernon** [comment]
I gave this another go, and came to the conclusion that doing this would be a huge pain, unless the makefile system gets a big overhaul, to make things like this easier. The problem is, that the keymaps and keyboards are built in a for loop, and make gets called recursively many times, and the exit status would need to be bubbled up. That's ugh...

A better way would be to use dependencies, such that `make keyboards/ergodox/keymaps/algernon` would compile just that, and `make keyboards/ergodox` would be a rule that depends on all the keymaps, and does nothing else.

This would require a major overhaul of the build system, and I'm not prepared for that at the moment. If anyone finds a way to only fail at the very end, and still keep the current fail-early behaviour as an option, without sacrificing many goats to the gods of Make, please let me know.

Closing the PR, because I'm not able to make it work with the resources I have.

**Pull request closed without merging**
