### PR TITLE
ergodox: Update my keymap to v1.5

### PR DESCRIPTION
**Pull request by algernon**
Major changes include:

* The **1HAND** layer has been removed.
* A `Delete` key is now available on the right thumb cluster.
* The **ADORE** layer received a major update, see the updated layout image.
* It is now possible to enable automatic logging for the **ADORE** layer, by setting the `ADORE_AUTOLOG` makefile variable to `yes` when compiling the keymap. It is off by default.
* The `~` key and the `Media Next/Prev` key have been swapped on the **base** layer.
* On the **ARROW** layer, `Backspace` has been replaced by `Enter`.
* There is some experimental support for entering Unicode symbols.

Note that the `keymap.c` diff is rather large, and appears to replace pretty much the whole file. This is because a pull request changed some whitespace, and this one also restores that to what I have in my repo.

### CODE REVIEW

**Comment by algernon** [comment]
This pull request has been made with lots of 😙, because I wanted to build a ☃. No unicode codes were entered while writing this comment, it was all text.

(Browsers are also 💩, because they need longer delays to enter these symbols than any other software I tried them with...)

**Comment by iFreilicht** [comment]
How are you implementing unicode input without using the `UNICODE(n)` macro?

**Comment by algernon** [comment]
My solution works in a similar way, under the hood: it presses a shortcut that the OS recognises as unicode input, and then sends the code, finished by space or enter. The difference is that for the `UNICODE()` macro, you need to use codes, and bind it to a key. With my solution, you have a key that triggers unicode symbol mode, and you enter the symbol's **name**, and the firmware translates that to a code.

Mine can also enter codes larger than 16 bits, which the `UNICODE()

**Comment by ezuk** [comment]
So awesome!! Merging!

**Pull request merged**
