### PR TITLE
Circuit keymap for Planck keyboard

### PR DESCRIPTION
**Pull request by mld2443**
* Layout has image and readme, as well as documentation in the code.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Cool! Thanks :)

**Comment by jackhumbert** [comment]
Would you mind pulling the latest changes to the tap dance stuff (from master)? It looks like this keymap breaks with them.

**Comment by mld2443** [comment]
I'll take a look

**Comment by mld2443** [comment]
It appears a kind fellow fixed it for me.

**Pull request merged**
