### PR TITLE
Minor changes to keymaps and other files

### PR DESCRIPTION
**Pull request by Xyverz**
Added a readme.md and updated the comments in the keymap.c for my ErgoDox layout.

Minor changes to my Planck layout.

Minor changes to my Phantom layout.

### CODE REVIEW

**Comment by iFreilicht** [comment]
You should look through the test results, there are a lot of warnings about excess list initialiser elements popping up.

**Comment by Xyverz** [comment]
I mentioned that with my previous pull request.

This pull request adds notes that my ErgoDox keymap isn't compatible with
the Infinity ErgoDox and why.

**Comment by jackhumbert** [comment]
Gonna go ahead and merge this in - I don't think travis is able to pull the updates.

**Comment by jackhumbert** [comment]
Also thanks :)

**Comment by Xyverz** [comment]
Thanks, Jack. I'm going to work on creating a keymap.c that will work with both keyboards. I'll make sure it compiles cleanly on my machine without error for both versions - even though I don't have an Infinity to test it on - before I make another pull request.

**Comment by Xyverz** [comment]
In the process of making my keymap dual-purpose. I have no means to test it on the Infinity, but it does at least compile without errors.

**Pull request merged**
