### PR TITLE
Add infinity ergodox

### PR DESCRIPTION
**Pull request by fredizzimo**
This is a working version of one side of the Infinity Ergodox. I just flashed the firmware and tried it :)

The next step is to add the serial protocol, so that both hands can be used. 

Currently it's located in it's own keyboard folder, but at some point, I we might want to try to merge it with the Ergodox EZ, as a subproject.

### CODE REVIEW

**Comment by jackhumbert** [comment]
Awesome :)

**Comment by sethbc** [comment]
what's the idea here as far as both sides working - would we be flashing one distinct layout to each hand ala kiibohd/controller?

**Comment by fredizzimo** [comment]
Hi @sethbc,

The most recent merged version already supports the link between the two sides. In fact almost everything is working, and I'm currently making it a subproject of Ergodox, so that both the EZ and Infinity can share the same keymaps. However, I want to make some improvements to the visualization code before recommending too many people to use it, since it could have some effects on custom keymaps.

And now to the actual question. The master is in complete control of the layout, and the layer switching. Only the physical key states are sent over the serial link after debouncing, so the slave does it's own debouncing for its keys. This means, that if you are only doing keymap changes, it's enough to flash just the master half. 

The master can be changed by setting the makefile variable master=left or master=right, by default it's left.

Doing it this way, allows the QMK firmware to work almost completely as it is, without modifications. After the scanning phase, the master sees both (or all, when support for chaining is added) halves as a one big keyboard.

Technically the slave runs exactly the same code, including the layer switching, but the result of that is not sent anywhere, so it's completely invisible.

One exception to this is the visualizer, it does its own processing in each half, in order to avoid having the master needing to control both of the LCD screens for example. Instead the master only sends all the required meta-data, like current_layer to the slave visualizer, and the slave will therefore react properly to the changes.

In practice, this all means that for simple keymap changes, you only need to flash the master. When you upgrade the codebase to a new version(or applying a ready compiled keymap), you should flash both sides though, since there might be changes to the actual protocol between the two halves. You also need to flash both halves when doing changes to the visualizer.

**Comment by sethbc** [comment]
makes sense, thanks for the detailed explanation - as an aside, at some point we should pillage some of the GH issues/comments into documentation.  have a bunch of other documentation fixes i've spotted along the way (there are a ton of broken links from the recent refactor of code/movement of readmes) so maybe i'll start collecting them and open PRs as i get to certain points.  (Of course, this is all assuming my day job isn't 24/7 - and it has been that and more recently).

**Pull request merged**
