### PR TITLE
Bépo with firmware remapping for software CSA layout

### PR DESCRIPTION
**Pull request by DidierLoiseau**
This is the keymap I have been using for months, but never took the time to make this PR – outside providing the header for the layout in PR #194.

It is designed to be used with the French [BÉPO](http://bepo.fr) layout, see the readme.md for more details (though I wrote most of it in French since it is the target audience).

It's main peculiarity is that it integrates a firmware switch to use it with the Canadian Multilingual layout (CSA) on OS side.

Outside the keymap itself, this PR provides `keymap_canadian_multilingual.h` with all keycodes for the CSA layout.

### CODE REVIEW

**Comment by ezuk** [comment]
I love it! Thank you so much, @DidierLoiseau! I'm a big fan of I18n and it's great to see a comprehensive keymap like this.

**Comment by DidierLoiseau** [comment]
Thanks, @ezuk :) Don't hesitate if you have question on some implementation choices (or suggestions).

Also, did you notice how I declared Unicode characters?
```
const uint16_t unicode_chars[] = {
        [UC_NDSH] = L'–',
        [UC_MDSH] = L'—',
        [UC_ELPS] = L'…',
};
```
I still have a custom implementation of Unicode though, which does not work in a lot of cases (Office apps). I'd like to migrate it to the QMK one but is it documented somewhere? I only saw the discussions in #333 and from what I understand it doubles the memory footprint of the keymaps, by switching the keycodes to 32 bits. @jackhumbert maybe?

**Comment by algernon** [comment]
You can always use macros, that call `unicode_input_start`, then type the code, and call `unicode_input_finish` - it won't double the memory footprint then, and does essentially the same thing. As an example, [here](https://github.com/algernon/ergodox-layout/blob/7bc86585d29e1a940d413ab4389de17036beebba/keymap.c#L1017-L1022) is how I enter the `λ` symbol.

You will need to call `set_unicode_input_mode(UC_WIN)` to put the unicode system into windows mode - sadly inputting unicode is not the same across operating systems, and QMK's default is the Mac.

**Comment by DidierLoiseau** [comment]
@algernon Thanks for the suggestion. I just had the look at the implementation and it is exactly the same as mine (for Windows, at least).

The thing is that I had investigated this quite a bit, and I could never make it work properly in Office 2013 apps (except Excel, strangely), though it works in other apps like Firefox. The Alt+X technique appears to work (see [wikipedia](https://en.wikipedia.org/wiki/Unicode_input#Hexadecimal_code_input)), but having to choose the correct one every time would be a problem.

**Pull request merged**
