### PR TITLE
Teckinesis for ErgoDox EZ

### PR DESCRIPTION
**Pull request by willwm**
The Ordinary Layout + original TECK 209 + Kinesis Advantage = teckinesis.

Thanks to @nrrkeene for providing such a great layout to start from, and of course, to @jackhumbert for the qmk_firmware repo! =)

teckinesis-base

### CODE REVIEW

**Comment by nrrkeene** [comment]
Sweet. Thank you for the kind words. This is the first derivative layout that I'm aware of. Have you had any trouble getting a single-quote char when you type fast expecting a double-quote char? I never solved that problem with the shift keys having dual purpose with char keys.

**Comment by willwm** [comment]
I haven't encountered the single/double quote issue yet, likely because my
typing speed hasn't quite returned to normal yet. :-)

On a related note, however, I have encountered an issue where Fx registers
as x (F2 as 2, for example) when I try to activate the Symbol Shift layer
and the number quickly. (If I hold the Symbol Shift key, however, it seems
to not be an issue.)

**Comment by ezuk** [comment]
@willwm - this is awesome! My only question/concern: I suspect advantage_layout_win.png is a copyrighted image. If we don't have rights to use it, would you mind dropping it from the PR? I wouldn't want to violate any intellectual property laws. :)

**Comment by willwm** [comment]
@ezuk - Sure thing! (Good catch, btw!) I'll update the pull request shortly with the file removed. :-)

**Comment by ezuk** [comment]
@willwm awesome! :tada:

**Pull request merged**
