### PR TITLE
adapts unicode to quantum.c

### PR DESCRIPTION
**Pull request by jackhumbert**
Pulls in changes made by @mecanogrh to the new quantum.c format, and moves some things around for up to 0x7FFF unicode support.

@mecanogrh, feel free to pull this branch's (pr/327) changes, and make commits to the branch on your fork.

### CODE REVIEW

**Comment by mecanogrh** [comment]
That's nice :) thanks for this. 
I have since worked on full unicode tables support and 32 bit, got it working through pgm_read_dword and adding a specific action_kind_id in tmk_core/common/action_code.h, there I had to switch the id/kind  with the params in the structs of the action_t union to avoid the bit shift >= width limitation so everything plays nice.
But in the process I broke the ability to pile up mods through bit masking i.e. I have #define in my keymaps like #define LSG(kc) (MOD_LSFT|MOD_LGUI, KC_##kc) which are no longer working.
As soon as I fix it, I'll add ifdef for full Unicode (because I guess it is taking much more space than actual Unicode) and submit the code.

**Comment by jackhumbert** [comment]
I think I have most of that implemented in the user_functions branch, but I'd like to hold off on the 32bit keycodes for now - that's gonna increase everyone's footprint, and I'd like to handle it so that things can be slimmed down if need.

**Comment by eltang** [comment]
Just a quick question: Why do the Unicode values have to be stored in the keymap? I'm thinking that they can be stored in a separate LUT.

**Comment by jackhumbert** [comment]
I'm really looking for full unicode support, meaning you can send all of the codes, which would require the same space in the keycode mapping.

I already have some shortcuts like `UC_a`.

**Comment by eltang** [comment]
There would still be full support. See this.

```c
const macro_t * action_get_macro(keyrecord_t *record, uint8_t id, uint8_t opt) {
    switch (id) {
        case 0:
            unicode_send(pgm_read_dword(&unicode_lut[0]));
            break;
    }
}

const uint32_t unicode_lut[] PROGMEM {
    [0] = 0xFF
}
```

**Comment by jackhumbert** [comment]
That's no different from `unicode_send(0xFF)`, which is what I'm trying to avoid, and why they've been implemented as keycodes.

**Comment by jackhumbert** [comment]
Merging this in now. It also changes up the order of some of the QMK keycode shortcuts, so if those start acting funny (they shouldn't), the problem may be from this PR.

**Comment by mecanogrh** [comment]
For info, full unicode support (32 bit) footprint on a planck 32U4:
`0x5780 bytes written into 0x7000 bytes memory (78.12%).`
other active options being MOUSEKEY, EXTRAKEY, COMMAND and BACKLIGHT

**Comment by coderkun** [comment]
I would like to test your Unicode changes. Should Unicode work on the master branch already (with characters like 0x2713)?

Would you mind verifying the steps needed for the Ergodox EZ?:
* Makefile:
  * `UNICODE_ENABLE = yes`
* Keymap:
  * `#include "quantum.h"`
  * add `set_unicode_mode(UC_LNX);` to `matrix_init_user(void)`
  * map some key e. g. `UC(0x2713)`

**Comment by jackhumbert** [comment]
@mecanogrh this should vary depending on how many layers you have, along with the keyboard size as well. Sending larger ones as macros should be an easy way to support all of unicode, via a `send_unicode` function - regretting taking that out now :)

@coderkun that sounds correct! Let us know what happens - I haven't been able to test things on Linux yet, since things vary so much.

**Pull request merged**
