### PR TITLE
Adding Ergodox Dvorak Programmer layout

### PR DESCRIPTION
**Pull request by lucwastiaux**
Adding my Dvorak Programmer layout. I believe this layout will be interesting to anyone who spends a lot of time on the command line, with a number of bash-specific shortcuts on my SHELL_NAV layer.

Also added .stfolder to the .gitignore, I use the Syncthing peer to peer syncing solution to build my keymaps remotely so I need to ignore this file. Hopefully this can go in.

### CODE REVIEW

**Comment by lucwastiaux** [comment]
Hi, any concerns with merging this ?

**Comment by algernon** [comment]
As a comment from a passer-by, the shell/key nav layer ideas are terrific, I may end up borrowing them. Thanks! :)

**Comment by lucwastiaux** [comment]
> As a comment from a passer-by, the shell/key nav layer ideas are terrific, I may end up borrowing them. Thanks! :)

thanks for noticing ! The idea of of a key navigation and key selection layer originate from my experiments with the Pok3r. It has no arrow keys, but they are available in the function layer. Having the capslock key be a function key that toggles a layer is something quite natural and much more useful than a normal caplock.

I got used to this idea that the left hand enables layers, and the right hand presses keys in the newly switched layer. Overall the goal is to avoid as much as possible moving away from the home row.

**Comment by ezuk** [comment]
No concerns whatsoever @lucwastiaux! This is super cool! Merging :)

**Pull request merged**
