### PR TITLE
Add warning when submodules are not updated

### PR DESCRIPTION
**Pull request by fredizzimo**
This will print a warning when the user haven't updated the submodules. It also tells what to do in that case. This will hopefully avoid a lot of confusion due to the added ChibiOS submodule.

### CODE REVIEW

**Comment by fredizzimo** [comment]
Ok, it seems like it fails in the travis environment. It works on my Cygwin installation. I will try the Vagrant Ubuntu image, to see if I can reproduce it.

**Comment by algernon** [comment]
This is a `bash` vs `sh` thing, whatever shell Travis uses, does not like `${x:0:1}` (or the `[[ ... ]]` construct, or both). I haven't used bash in like a decade, what is this supposed to do? Perhaps I can suggest an alternative that plain `sh` will understand too...

**Comment by fredizzimo** [comment]
Yes, I figured out that much myself, adding the following to the top of the make file is supposed to make it use bash instead
```
SHELL := /bin/bash
```
But for some reason it's not working.

The function is just supposed to loop through all lines of  the `git submodule status --recursive` output. And If the line starts with anything else than a space, it's supposed to write the warning.

**Comment by algernon** [comment]
How about this (instead of the if):

```sh
case "$x" in \
  " *") ;; \
  *) printf "$(MSG_SUBMODULE_DIRTY)";; \
esac
```

**Comment by fredizzimo** [comment]
Thanks @algernon, your suggestion almost worked, I only had to modify it slightly and escape the space instead of quoting it

**Comment by jackhumbert** [comment]
Cool! Thanks guys.

**Pull request merged**
