### PR TITLE
Fixed Setup Script

### PR DESCRIPTION
**Pull request by IBNobody**
Drastically rewrote the path script to handle Explorer's stubborn grasp of EnvVars. Tested on Win7.

### CODE REVIEW

**Comment by NoahAndrews** [comment]
Please don't merge this quite yet. I've got a few questions.

**Comment by NoahAndrews** [comment]
What's the purpose of the ping commands?

**Comment by NoahAndrews** [comment]
FTR Jack, I don't see a problem with merging this. I don't understand every bit of it yet, but I basically understand it, and it was clearly well-designed.

**Comment by IBNobody** [comment]
Since Windows didn't have a WAIT command until later, a hack is to use ping to localhost. The time between each ping is roughly 1s. If we want to assume everyone is on Win7 or greater, we can use TIMEOUT.

**Comment by NoahAndrews** [comment]
Ah right, of course

**Comment by NoahAndrews** [comment]
It might not be quite as linear and easy to read as my version, but wow. This has a lot of smart ideas, and it's waaay more modular and error-resilient. Great work.

**Comment by jackhumbert** [comment]
Awesome :) merging!

**Pull request merged**
