### PR TITLE
add coderkun’s ErgodoxEZ keymap (Neo2)

### PR DESCRIPTION
**Pull request by coderkun**
This is the first version of my keymap for the [Ergodox EZ](https://www.indiegogo.com/projects/ergodox-ez-an-incredible-mechanical-keyboard) which is based on the [Neo](http://neo-layout.org/) layout. The purpose of this pull request is to share the layout—as the README suggests.

I itend to add variuos Unicode characters to the second layer but I could not get Unicode to work, yet. So this is futurue work.

Comments and feedback are welcome!

### CODE REVIEW

**Comment by jackhumbert** [comment]
Sweet! Thanks for sharing.

(Off-topic) This inspired #90 - it'd be nice to not have to worry about the Makefile/changes to it when compiling/sharing different layouts.

**Comment by coderkun** [comment]
Good idea. Some Makefile settings—like the Unicode option—depend on the keymap.

**Comment by ezuk** [comment]
Awesome stuff! Merging this in, thank you @coderkun.

**Comment by DidierLoiseau** [comment]
I was looking for this PR as it provided the only keymap that uses `UC`, and I wanted to check if it was working but apparently not.

In fact, the description of UC indicates it:
```
// For sending unicode codes.
// You may not send codes over 1FFF -- this supports most of UTF8.
// To have a key that sends out Œ, go UC(0x0152)
#define UNICODE(n) (n | 0x8000)
#define UC(n) UNICODE(n)
```
so the characters used in this keymap (`0x2713` and `0x2715`) would not be allowed.

“_this supports most of UTF8_” is a bit funny as this covers only 8192 characters out of the 120 000+ that unicode defines :-) A lot of interesting characters are thus above 0x1FFF (I would personally be interested in [general punctuation](http://unicode-table.com/en/blocks/general-punctuation/)).

Actually, I have checked the implementation of unicode and the threshold seems to be 0xFFF, as at some point the character is put inside an `action_t` where the code is always `1111` (`ACTION_FUNCTION`). Except by changing the definition of `action_t`, I think there will be no way around this.

By the way I figured it was very easy to define characters in the code like this:
```
uint16_t dots = L'…'; // U+2026
```
which declares a wide character (i.e. unicode code point), instead of a UTF-8 character. I didn't check what happens for characters above 0xFFFF though – probably just a warning so pay attention.

**Comment by ezuk** [comment]
Thanks @DidierLoiseau! In general, very awesome work on the repo these days, I really appreciate all of your contributions!

@jackhumbert - what do you think? Just looping you in, in case you missed this.

**Comment by coderkun** [comment]
Putting some Unicode chanacters in the layout was more like a test for me. I know they don’t work but I was hoping someone would come along and put some work into the Unicode implementation ;)

**Pull request merged**
