### PR TITLE
Add ChibiOS support for QMK (WIP)

### PR DESCRIPTION
**Pull request by fredizzimo**
This is work in progress of adding ChibiOS for QMK. So please don't merge it yet.

I'm making the pull request, so that I can test updating the Travis scripts.

Everything seems to work locally, well at least it compiles, but I haven't been able to test anything on real hardware yet, since I don't own any of the keyboards. So the first thing to do before merging, would be to have someone else test that the normal AVR keyboards still works.

The new ChibiOS keyboards, probably won't work yet, although they do compile. But it wouldn't hurt if someone could test the Infinity 60% (infinity_chibios) keyboard. 

There's also several "one key" example keyboards, that are mostly there for testing different hardware that ChibiOS supports. It's probably worth keeping them for at least a while, when I'm working on it. And I can also convert them into the new suproject format. After everything is working, they would mostly serve as examples, so they could either be kept as such or deleted.

Most changes are taken directly from TMK using cherry picking. But I have quite heavily refactored the make files to avoid duplication, and make the all- targets work.

The next steps are probably to try to add one hand of Ergodox, without LCD or LED support. After that I'm planning to refactor the matrix scan code, so that it can be shared like the rest of the QMK keyboards. This pull request could probably be merged before that, but it would also be possible to continue updating it, and only merge it when I have confirmed that the Ergodox is working.

Any comments, or anything else that you think that should be done?

### CODE REVIEW

**Comment by jackhumbert** [comment]
Nice! This is looking good.

With the subproject stuff, we could stick the test boards in something like `/keyboards/test/` and have them compile still. There will need to be a `test.c` in the directory, though.

It looks like the subproject testing is what's failing on travis - currently it assumes all folders in the keyboard folder are subprojects unless you tell it otherwise by adding it to `rules.mk:L625`. This is something that really needs to change to a silent fail in the future.

**Comment by fredizzimo** [comment]
Seems like all the tests passes now, so after a couple of AVR based keyboards have been tested, I think it's good to be merged. Although the number of changes are huge, there's not really much that should affect those, so I don't see any reason why they wouldn't. Still there's a chance that I have messed up some compiler setting or something.

I fixed the suproject issue in [this](https://github.com/jackhumbert/qmk_firmware/pull/465/commits/95f636580b8be5beaf057dca8d37aa7714e66fc2) commit, by making it consider only sub-folders with Makefiles in them.

I will start converting the one key tests keyboards to subprojects now, but I'll do it in a separate branch, so I can send a separate pull request for that, which should be much smaller and easier to review. And the same thing with future changes. There's still the option to merge those into this pull requests, if you decide to not merge now, but do it at a later point.

**Comment by fredizzimo** [comment]
Ah, before we merge it, we should probably add some documentation. Maybe something similar to what I wrote [here](https://github.com/fredizzimo/infinity_ergodox) in the Git Notes, and the Prerequisites sections.

For the ChibiOS submodules. I think all normal keyboards should work without updating them, but if someone runs make-all-keyboards, then the submodules need to be updated correctly.

The same thing for the compiler, everything should work without it, but if you want to build a ChibiOS based board, you will need it.

The Vagrant image, should also be updated with the correct packages installed. 

I can update the package, and also write a first draft of the documentation. But @ezuk probably wants to edit it to his standards afterwards.

We could also potentially skip the submodule documentation, if we decide to go with subtrees immediately. In that case I can convert the submodules to subtrees before the merge.

**Comment by jackhumbert** [comment]
Thanks for fixing the subproject stuff :)

Let's merge this now, and we'll work on the doc a bit later - I'll make an issue for that.

**Pull request merged**
