### PR TITLE
Add `quantum/keymap_extras/keymap_plover.h` and a keymap.

### PR DESCRIPTION
**Pull request by Twey**

### CODE REVIEW

**Comment by ezuk** [comment]
@jackhumbert could you take a look at the change to `keymap_plover.h` just for sanity?

@Twey thank you for contributing! Could you also add the hex file? `git add -f` would let you do it.

**Comment by jackhumbert** [comment]
Looks good to me :)

**Comment by Twey** [comment]
Done. It's an addition, not a change — existing Plover maps refer to QWERTY keys, but I preferred to have meaningful names à la `keymap_dvorak.h`.

**Comment by ezuk** [comment]
Awesome, thank you! Merging.

**Pull request merged**
