### PR TITLE
TypeMatrix 2030 Layout for ErgoDox EZ

### PR DESCRIPTION
**Pull request by DidierLoiseau**
This is a [TypeMatrix 2030](http://typematrix.com/2030/features.php)-like layout for the ErgoDox EZ. The idea was to implement a layout that is as close as possible to the TM2030, such that it would be easy to switch between it and the ErgoDox. No _fancy_ features have been implemented, this is intended to be a base for further customization if desired.

Most of the TM2030 features are supported except
* application shortcut keys
* automatic window switching (alt-tab key, at the left of the space key)
* show desktop key (at the right of the space key)
* 102/106 modes

Dvorak mode is even supported by pressing Magic+1 :-)

Some keys had to be moved around to fit into the ErgoDox, especially the F1-F12 keys and the arrow keys. A full description is available at the top of the file.

Now I'm looking for some feedback :-)

I suppose the file would have to be renamed before merging, maybe something like `tm2030.c` would be fine?

For the record, I'm using this layout with the French [BÉPO](http://bepo.fr/wiki/Accueil) OS layout. The main issue I have is that the “m” falls on the `SFT_T(KC_QUOT)` key, which is somewhat unreliable. I have already set `TAPPING_TERM` to 140 in my builds but that's not always ideal. I'm not sure `SFT_T` is really compatible with touch typing…

I will also probably implement a BÉPO layout at firmware level later on, for using with AZERTY as OS layout.

### CODE REVIEW

**Comment by ezuk** [comment]
This is super nice!! I love it! :)

I just restructured the keymaps directory and wrote up clearer guidelines on how to contribute -- just a couple of quick things I suggest adding, nothing too crazy I hope: Check it out [here](https://github.com/jackhumbert/qmk_firmware/tree/master/keyboard/ergodox_ez) under "Contributing your keymap"

What do you think? If you're cool with slightly tweaking the format to follow this convention, I'd love to merge this up.

**Comment by ezuk** [comment]
Oh and another possible thought for your readme, just a suggestion: It would be cool if you explained what's interesting about the TypeMatrix layout also for people who don't know the original at all. Just an idea, might make more people give this a try :)

**Comment by DidierLoiseau** [comment]
@ezuk I have now updated my branch following the new guidelines and your comments.

**Comment by ezuk** [comment]
@DidierLoiseau - this is so great!! I love it, thank you! Merged.

**Pull request merged**
