### PR TITLE
The Ordinary Layout is the unsurprising layout

### PR DESCRIPTION
**Pull request by nrrkeene**
I am deficient in my ability to use Github but I believe I've made a pull request that is adequate.

### CODE REVIEW

**Comment by ezuk** [comment]
Thank you, @nrrkeene! @jackhumbert any idea why CI is bombing?

**Comment by algernon** [comment]
CI bombs, because the keymap still needs to be updated: not only did the keyboard move from `keyboards/ergodox_ez`, the header also changed from `ergodox_ez.h` to `ergodox.h`, and this keymap is still using the old name.

**Comment by ezuk** [comment]
Thanks @algernon! @nrrkeene - any chance you could update accordingly?

**Comment by fredizzimo** [comment]
The folders appears to be right, so the only thing that needs to be changed is to change the `#include "ergodox_ez.h"` to `#include "ergodox.h"`

**Comment by nrrkeene** [comment]
I will make the change when I catch my breath this weekend

**Comment by nrrkeene** [comment]
Does this pull request now automatically include the two commits I just made? 8f78ba1 and 6a9a6b9
? If so, I made the required change and it builds for me and works on my keyboard.

**Comment by fredizzimo** [comment]
Yes it does, and all the checks are passing now.

**Comment by jackhumbert** [comment]
Prefect! Thanks :)

**Pull request merged**
